`timescale 1ns/1ps
//
// Exercises the CPU against a behavioral memory implementing mem_bus's
// contract (answer the cycle after the access, holding between accesses), so
// a failure here points at the CPU rather than the bus. Two layers:
//
// Directed programs, hand-encoded halfwords generated by the repo's own
// assembler (scripts/lib/v810.ts, itself tested against beetle-vb's
// decoder), pin the machinery ROMs can't reach or can't distinguish: the
// documented reset state, system register quirks, TRAP/RETI round trips
// with the exact saved PC/PSW/ECR, zero-division and illegal-opcode entry,
// the duplexed and fatal escalations, and HALT against every interrupt
// acceptance condition -- ID, level masking, and the wake sequence.
//
// Then the built cpu-alu, cpu-branch and busmap images run to completion:
// each writes check numbers to WRAM 0x05000000 as it goes and 0x600D on
// success, so the bench reports the exact failing check when one spins.
// Build them first: a missing hex fails with a message, not silence.
//
// Programs load at the reset vector's trampoline (the same three halfwords
// the packer's jumpFar emits), so every run enters through the real reset
// path: PC 0xFFFFFFF0, mirrored into the top of the ROM.
//

module cpu_tb;

    localparam ROM_HWORDS  = 32768;   // 64KB, the directed-test ROM size
    localparam WRAM_HWORDS = 32768;

    reg clk = 1'b0;
    always #5 clk = ~clk;

    // Architectural time at the hardware's own 625/1248 ratio -- including
    // its two adjacent-clock enables per window, the tightest spacing the
    // per-CE machine ever sees -- so every drain and walk runs at a
    // realistic pace and the timing assertions below measure exactly what
    // the Pocket would.
    reg        ce = 1'b0;
    reg [10:0] ce_acc = 11'd0;
    always @(posedge clk) begin
        if (ce_acc + 11'd625 >= 11'd1248) begin
            ce_acc <= ce_acc + 11'd625 - 11'd1248;
            ce     <= 1'b1;
        end else begin
            ce_acc <= ce_acc + 11'd625;
            ce     <= 1'b0;
        end
    end

    reg reset_n = 1'b0;
    reg ready = 1'b1;
    reg irq_valid = 1'b0;
    reg [3:0] irq_level = 4'd0;

    wire        req, we;
    wire [26:1] a;
    wire [1:0]  be;
    wire [15:0] wd;
    reg  [15:0] rd;
    wire [31:0] dbg_pc;
    wire        dbg_halted;

    // The real timer answers region 2 and interrupts at level 1, wired
    // the way core_top wires it. The manual irq regs still drive the
    // directed scenarios, which never arm the timer; the two never
    // request at once.
    wire [15:0] timer_rdata;
    wire        timer_irq;

    timer u_timer (
        .clk(clk),
        .reset_n(reset_n),
        .ce(ce),
        .sel(req && a[26:24] == 3'd2),
        .addr(a),
        .we(we),
        .be(be),
        .wdata(wd),
        .rdata(timer_rdata),
        .irq(timer_irq)
    );

    // The real game pad answers the same region at its own registers and
    // interrupts at level 0, again wired the way core_top wires it. Its
    // report is driven straight from the bench, standing in for
    // host_pad_map, which src/tests/game_pad.v owns.
    reg  [15:0] pad_buttons = 16'h0002;
    wire [15:0] pad_rdata;
    wire        pad_irq;

    game_pad u_pad (
        .clk(clk),
        .reset_n(reset_n),
        .ce(ce),
        .sel(req && a[26:24] == 3'd2),
        .addr(a),
        .we(we),
        .be(be),
        .wdata(wd),
        .rdata(pad_rdata),
        .buttons(pad_buttons),
        .irq(pad_irq)
    );

    reg rd_misc = 1'b0;   // last access hit region 2: the timer answers
    always @(posedge clk) if (req) rd_misc <= a[26:24] == 3'd2;

    // The region's two devices decode disjoint registers, so one answer is
    // the other's zero -- core_top merges them the same way.
    wire [15:0] misc_rdata = timer_rdata | pad_rdata;

    cpu dut (
        .clk(clk),
        .ce(ce),
        .reset_n(reset_n),
        .req(req),
        .addr(a),
        .we(we),
        .be(be),
        .wdata(wd),
        .rdata(rd_misc ? misc_rdata : rd),
        .ready(ready),
        .irq_valid(irq_valid || timer_irq || pad_irq),
        .irq_level(irq_valid ? irq_level : timer_irq ? 4'd1 : 4'd0),
        .dbg_pc(dbg_pc),
        .dbg_halted(dbg_halted)
    );

    // Behavioral memory: ROM in region 7 mirrored by rom_mask, work RAM in
    // region 5 mirrored by its size, zero from everything else. Writes into
    // region 0 are captured for the fatal-exception check. The answer lands
    // the cycle after the access and holds, like mem_bus.
    reg [15:0] rom  [0:ROM_HWORDS-1];
    reg [15:0] wram [0:WRAM_HWORDS-1];
    reg [15:0] region0 [0:7];
    integer    rom_mask;
    reg [15:0] status;   // last halfword written to WRAM 0x05000000

    // Architectural-cycle timestamps of every status write: the timing
    // scenarios read cost differences straight off consecutive markers.
    integer ce_ticks = 0;
    integer marks [0:15];
    integer mark_n = 0;

    always @(posedge clk) begin
        if (ce) ce_ticks = ce_ticks + 1;
        if (req && we && a == 26'h2800000 && be[0]) begin
            if (mark_n < 16) marks[mark_n] = ce_ticks;
            mark_n = mark_n + 1;
        end
    end

    always @(posedge clk) begin
        if (req) begin
            if (we) begin
                case (a[26:24])
                    3'd5: begin
                        if (be[0]) wram[a[15:1]][7:0]  <= wd[7:0];
                        if (be[1]) wram[a[15:1]][15:8] <= wd[15:8];
                        if (a[23:1] == 23'd0) begin
                            if (be[0]) status[7:0]  <= wd[7:0];
                            if (be[1]) status[15:8] <= wd[15:8];
                        end
                    end
                    3'd0: if (a[23:1] < 23'd8) region0[a[3:1]] <= wd;
                    default: ;
                endcase
            end
            case (a[26:24])
                3'd7:    rd <= rom[a[26:1] & rom_mask];
                3'd5:    rd <= wram[a[15:1]];
                default: rd <= 16'd0;
            endcase
        end
    end

    // ------------------------------------------------------------------
    // Scenario plumbing
    // ------------------------------------------------------------------

    integer dp;   // deposit pointer, in halfword indexes

    task automatic prog_h(input [15:0] value);
        begin
            rom[dp] = value;
            dp = dp + 1;
        end
    endtask

    // Hold reset and wipe the machine. The reset vector gets the packer's
    // jumpFar-to-0x07000000 trampoline; programs then deposit at index 0.
    task automatic restart;
        integer i;
        begin
            reset_n   = 1'b0;
            ready     = 1'b1;
            irq_valid = 1'b0;
            irq_level = 4'd0;
            for (i = 0; i < ROM_HWORDS; i = i + 1) rom[i] = 16'hxxxx;
            for (i = 0; i < WRAM_HWORDS; i = i + 1) wram[i] = 16'hxxxx;
            for (i = 0; i < 8; i = i + 1) region0[i] = 16'hxxxx;
            status   = 16'hxxxx;
            rom_mask = ROM_HWORDS - 1;
            rom['h7FF8] = 16'hbc20;   // movhi 0x0700, r0, r1
            rom['h7FF9] = 16'h0700;
            rom['h7FFA] = 16'h1801;   // jmp [r1]
            dp = 0;
            @(negedge clk);
        end
    endtask

    task automatic go;
        begin
            repeat (4) @(negedge clk);
            reset_n = 1'b1;
        end
    endtask

    task automatic wait_halt(input integer max_cycles, input string what);
        integer i;
        begin
            i = 0;
            while (!dbg_halted) begin
                @(negedge clk);
                i = i + 1;
                if (i > max_cycles)
                    $fatal(1, "%0s: no halt after %0d cycles, pc %08x status %04x",
                           what, max_cycles, dbg_pc, status);
            end
        end
    endtask

    task automatic wait_wake(input integer max_cycles, input string what);
        integer i;
        begin
            i = 0;
            while (dbg_halted) begin
                @(negedge clk);
                i = i + 1;
                if (i > max_cycles)
                    $fatal(1, "%0s: still halted after %0d cycles", what, max_cycles);
            end
        end
    endtask

    task automatic expect_gpr(input integer n, input [31:0] expected,
                              input string what);
        if (dut.gpr[n] !== expected)
            $fatal(1, "%0s: r%0d is %08x, expected %08x",
                   what, n, dut.gpr[n], expected);
    endtask

    task automatic expect_delta(input integer idx, input integer expected,
                                input string what);
        if (marks[idx] - marks[idx-1] !== expected)
            $fatal(1, "%0s: markers %0d-%0d are %0d cycles apart, expected %0d",
                   what, idx - 1, idx, marks[idx] - marks[idx-1], expected);
    endtask

    // Runs a built ROM image to its success halt. The image's own checks do
    // the judging; the status word carries the verdict.
    task automatic run_rom(input string name, input integer hwords,
                           input integer max_cycles);
        integer fd;
        string  path;
        begin
            restart();
            path = {"../.roms/", name, ".hex"};
            fd = $fopen(path, "r");
            if (fd == 0)
                $fatal(1, "%0s: cannot open %0s; run pnpm run build:roms first",
                       name, path);
            $fclose(fd);
            $readmemh(path, rom);
            rom_mask = hwords - 1;
            go();
            wait_halt(max_cycles, name);
            if (status !== 16'h600d)
                $fatal(1, "%0s: halted with status %04x at pc %08x, expected 600d",
                       name, status, dbg_pc);
        end
    endtask

    // Runs a built ROM to a status value instead of a halt, for an image
    // whose pass is a running display rather than a stop.
    task automatic run_rom_status(input string name, input integer hwords,
                                  input [15:0] want,
                                  input integer max_cycles);
        integer fd;
        string  path;
        begin
            restart();
            path = {"../.roms/", name, ".hex"};
            fd = $fopen(path, "r");
            if (fd == 0)
                $fatal(1, "%0s: cannot open %0s; run pnpm run build:roms first",
                       name, path);
            $fclose(fd);
            $readmemh(path, rom);
            rom_mask = hwords - 1;
            go();
            wait_status(want, max_cycles, name);
        end
    endtask

    // Waits for a running image to publish a status word, for a ROM whose
    // display loop answers more than once.
    task automatic wait_status(input [15:0] want, input integer max_cycles,
                               input string name);
        integer i;
        begin
            i = 0;
            while (status !== want) begin
                @(negedge clk);
                i = i + 1;
                if (i > max_cycles)
                    $fatal(1, "%0s: status %04x never became %04x in %0d cycles, pc %08x",
                           name, status, want, max_cycles, dbg_pc);
            end
        end
    endtask

    // ------------------------------------------------------------------
    // The scenarios
    // ------------------------------------------------------------------

    initial begin
        // D1: reset state, observed architecturally. The first fetch goes to
        // 0xFFFFFFF0 with the top five bits already gone, and the read-only
        // system registers carry their fixed values.
        restart();
        prog_h(16'h7545);  // stsr PSW,  r10
        prog_h(16'h7564);  // stsr ECR,  r11
        prog_h(16'h7586);  // stsr PIR,  r12
        prog_h(16'h75a7);  // stsr TKCW, r13
        prog_h(16'h75de);  // stsr 30,   r14
        prog_h(16'h75e8);  // stsr 8,    r15
        prog_h(16'h6800);  // halt
        ready = 1'b0;
        go();
        while (!req) @(negedge clk);
        if (a !== 26'h3FFFFF8)
            $fatal(1, "d1: first fetch at %07x, expected 3fffff8 (0xFFFFFFF0 masked)", a);
        repeat (5) begin
            @(negedge clk);
            if (!req || a !== 26'h3FFFFF8)
                $fatal(1, "d1: fetch changed while ready was low");
        end
        ready = 1'b1;
        wait_halt(2000, "d1");
        expect_gpr(10, 32'h0000_8000, "d1 PSW");
        expect_gpr(11, 32'h0000_FFF0, "d1 ECR");
        expect_gpr(12, 32'h0000_5346, "d1 PIR");
        expect_gpr(13, 32'h0000_00E0, "d1 TKCW");
        expect_gpr(14, 32'h0000_0004, "d1 sysreg 30");
        expect_gpr(15, 32'h0000_0000, "d1 reserved sysreg");

        // D2: system register quirks: register 31 reads back the absolute
        // value, ECR ignores LDSR, 29 is plain storage, PSW round-trips
        // through its mask.
        restart();
        prog_h(16'ha140); prog_h(16'hfff8);  // movea 0xFFF8, r0, r10 (-8)
        prog_h(16'h715f);                    // ldsr r10, 31
        prog_h(16'h757f);                    // stsr 31, r11
        prog_h(16'h7144);                    // ldsr r10, ECR
        prog_h(16'h7584);                    // stsr ECR, r12
        prog_h(16'h715d);                    // ldsr r10, 29
        prog_h(16'h75bd);                    // stsr 29, r13
        prog_h(16'hbdc0); prog_h(16'h0003);  // movhi 3, r0, r14
        prog_h(16'ha1ce); prog_h(16'h0009);  // movea 9, r14, r14
        prog_h(16'h71c5);                    // ldsr r14, PSW
        prog_h(16'h75e5);                    // stsr PSW, r15
        prog_h(16'h6800);                    // halt
        go();
        wait_halt(3000, "d2");
        expect_gpr(11, 32'h0000_0008, "d2 sysreg 31 abs");
        expect_gpr(12, 32'h0000_FFF0, "d2 ECR ldsr ignored");
        expect_gpr(13, 32'hFFFF_FFF8, "d2 sysreg 29");
        expect_gpr(15, 32'h0003_0009, "d2 PSW roundtrip");

        // D3: TRAP through both vector halves, RETI resuming, and the saved
        // PC/PSW/ECR checked from inside the handler.
        restart();
        prog_h(16'h4140);  // 00: mov 0, r10
        prog_h(16'h7145);  // 02: ldsr r10, PSW      (clear reset's NP)
        prog_h(16'h6003);  // 04: trap 3             -> 0xFFFFFFA0, code FFA3
        prog_h(16'h4201);  // 06: mov 1, r16
        prog_h(16'h6013);  // 08: trap 19            -> 0xFFFFFFB0, code FFB3
        prog_h(16'h41e2);  // 0A: mov 2, r15
        prog_h(16'h6800);  // 0C: halt
        dp = 'h7FD0;       // handler 0xFFFFFFA0
        prog_h(16'h7540);  // stsr EIPC,  r10
        prog_h(16'h7561);  // stsr EIPSW, r11
        prog_h(16'h7584);  // stsr ECR,   r12
        prog_h(16'h75a5);  // stsr PSW,   r13
        prog_h(16'h6400);  // reti
        dp = 'h7FD8;       // handler 0xFFFFFFB0
        prog_h(16'h75c4);  // stsr ECR, r14
        prog_h(16'h6400);  // reti
        go();
        wait_halt(4000, "d3");
        expect_gpr(10, 32'h0700_0006, "d3 EIPC (trap saves next PC)");
        expect_gpr(11, 32'h0000_0000, "d3 EIPSW");
        expect_gpr(12, 32'h0000_FFA3, "d3 ECR after trap 3");
        expect_gpr(13, 32'h0000_5000, "d3 PSW in handler (EP|ID)");
        expect_gpr(14, 32'h0000_FFB3, "d3 ECR after trap 19");
        expect_gpr(16, 32'h0000_0001, "d3 resumed after reti");
        expect_gpr(15, 32'h0000_0002, "d3 resumed after second reti");

        // D4a: divide by zero: reg2 untouched, restore PC is the divide
        // itself, so the handler halts rather than retrying forever.
        restart();
        prog_h(16'h4140);  // 00: mov 0, r10
        prog_h(16'h7145);  // 02: ldsr r10, PSW
        prog_h(16'h4145);  // 04: mov 5, r10
        prog_h(16'h4160);  // 06: mov 0, r11
        prog_h(16'h254b);  // 08: div r11, r10
        prog_h(16'h6800);  // 0A: halt
        dp = 'h7FC0;       // handler 0xFFFFFF80
        prog_h(16'h7584);  // stsr ECR,  r12
        prog_h(16'h75a0);  // stsr EIPC, r13
        prog_h(16'h6800);  // halt
        go();
        wait_halt(3000, "d4a");
        expect_gpr(10, 32'h0000_0005, "d4a reg2 untouched");
        expect_gpr(12, 32'h0000_FF80, "d4a ECR");
        expect_gpr(13, 32'h0700_0008, "d4a EIPC is the divide itself");

        // D4b: an invalid opcode (0x1B) raises illegal-opcode with the
        // faulting address saved.
        restart();
        prog_h(16'h4140);  // 00: mov 0, r10
        prog_h(16'h7145);  // 02: ldsr r10, PSW
        prog_h(16'h6c00);  // 04: opcode 0x1B, invalid
        prog_h(16'h6800);  // 06: halt
        dp = 'h7FC8;       // handler 0xFFFFFF90
        prog_h(16'h7584);  // stsr ECR,  r12
        prog_h(16'h75a0);  // stsr EIPC, r13
        prog_h(16'h6800);  // halt
        go();
        wait_halt(3000, "d4b");
        expect_gpr(12, 32'h0000_FF90, "d4b ECR");
        expect_gpr(13, 32'h0700_0004, "d4b EIPC is the illegal opcode");

        // D5: a trap inside a handler duplexes: FEPC pair, ECR's high half,
        // NP set, handler 0xFFFFFFD0.
        restart();
        prog_h(16'h4140);  // 00: mov 0, r10
        prog_h(16'h7145);  // 02: ldsr r10, PSW
        prog_h(16'h6000);  // 04: trap 0
        prog_h(16'h6800);  // 06: halt
        dp = 'h7FD0;       // handler 0xFFFFFFA0
        prog_h(16'h6001);  // trap 1 with EP set -> duplexed
        dp = 'h7FE8;       // handler 0xFFFFFFD0
        prog_h(16'h7584);  // stsr ECR,  r12
        prog_h(16'h75a2);  // stsr FEPC, r13
        prog_h(16'h75c5);  // stsr PSW,  r14
        prog_h(16'h6800);  // halt
        go();
        wait_halt(3000, "d5");
        expect_gpr(12, 32'hFFA1_FFA0, "d5 ECR carries both codes");
        expect_gpr(13, 32'hFFFF_FFA2, "d5 FEPC");
        expect_gpr(14, 32'h0000_D000, "d5 PSW (NP|EP|ID)");

        // D6: an exception with NP still set from reset is fatal: the cause
        // word, PSW and PC land at 0x0/0x4/0x8 and the CPU stops for good.
        restart();
        prog_h(16'h6000);  // 00: trap 0, NP set -> fatal
        go();
        wait_halt(3000, "d6");
        // the behavioral memory commits a write the clock after its req;
        // let the last fatal write land before reading it back
        repeat (2) @(negedge clk);
        if ({region0[1], region0[0]} !== 32'hFFFF_FFA0)
            $fatal(1, "d6: fatal cause word is %04x%04x, expected ffffffa0",
                   region0[1], region0[0]);
        if ({region0[3], region0[2]} !== 32'h0000_8000)
            $fatal(1, "d6: fatal PSW is %04x%04x, expected 00008000",
                   region0[3], region0[2]);
        if ({region0[5], region0[4]} !== 32'h0700_0002)
            $fatal(1, "d6: fatal PC is %04x%04x, expected 07000002",
                   region0[5], region0[4]);
        repeat (50) @(negedge clk);
        if (!dbg_halted) $fatal(1, "d6: fatal halt did not hold");

        // D7: HALT wakes on an accepted interrupt: entry saves the address
        // after the halt, raises the level, and RETI resumes there.
        restart();
        prog_h(16'h4140);  // 00: mov 0, r10
        prog_h(16'h7145);  // 02: ldsr r10, PSW
        prog_h(16'h6800);  // 04: halt
        prog_h(16'h4147);  // 06: mov 7, r10
        prog_h(16'h6800);  // 08: halt
        dp = 'h7F10;       // handler 0xFFFFFE20 (level 2)
        prog_h(16'h7564);  // stsr ECR,  r11
        prog_h(16'h7585);  // stsr PSW,  r12
        prog_h(16'h75a0);  // stsr EIPC, r13
        prog_h(16'h6400);  // reti
        go();
        wait_halt(2000, "d7 first halt");
        @(negedge clk);
        irq_level = 4'd2;
        irq_valid = 1'b1;
        wait_wake(1000, "d7 wake");
        irq_valid = 1'b0;
        wait_halt(3000, "d7 second halt");
        expect_gpr(10, 32'h0000_0007, "d7 resumed after reti");
        expect_gpr(11, 32'h0000_FE20, "d7 ECR");
        expect_gpr(12, 32'h0003_5000, "d7 PSW in handler (EP|ID|I=3)");
        expect_gpr(13, 32'h0700_0006, "d7 EIPC is the instruction after halt");

        // D8: the level mask: I=3 blocks level 2 and accepts level 3, and
        // acceptance raises I to level+1.
        restart();
        prog_h(16'hbd40); prog_h(16'h0003);  // movhi 3, r0, r10
        prog_h(16'h7145);  // 04: ldsr r10, PSW      (I=3, everything else 0)
        prog_h(16'h6800);  // 06: halt
        prog_h(16'h4149);  // 08: mov 9, r10
        prog_h(16'h6800);  // 0A: halt
        dp = 'h7F18;       // handler 0xFFFFFE30 (level 3)
        prog_h(16'h7565);  // stsr PSW, r11
        prog_h(16'h6400);  // reti
        go();
        wait_halt(2000, "d8 halt");
        @(negedge clk);
        irq_level = 4'd2;
        irq_valid = 1'b1;
        repeat (600) @(negedge clk);
        if (!dbg_halted)
            $fatal(1, "d8: level 2 woke a CPU masked at I=3");
        irq_level = 4'd3;
        wait_wake(1000, "d8 wake at level 3");
        irq_valid = 1'b0;
        wait_halt(3000, "d8 second halt");
        expect_gpr(10, 32'h0000_0009, "d8 resumed");
        expect_gpr(11, 32'h0004_5000, "d8 PSW in handler (EP|ID|I=4)");

        // D9: ID masks everything: a halt behind SEI never wakes, and that
        // is correct behavior rather than a hang.
        restart();
        prog_h(16'h4140);  // 00: mov 0, r10
        prog_h(16'h7145);  // 02: ldsr r10, PSW
        prog_h(16'h7800);  // 04: sei
        prog_h(16'h6800);  // 06: halt
        go();
        wait_halt(2000, "d9 halt");
        @(negedge clk);
        irq_level = 4'd3;
        irq_valid = 1'b1;
        repeat (900) @(negedge clk);
        if (!dbg_halted)
            $fatal(1, "d9: an interrupt woke a halt behind SEI");
        irq_valid = 1'b0;

        // T1: the cost model, measured. Each status write is a marker; the
        // difference between consecutive markers in architectural cycles is
        // the exact charge of the instructions between them. A marker pair
        // (addImm + stH) costs 10 cycles at the reset wait states (fetch-
        // bound: 3 for the addImm, max(1, 2x3)+1 for the store) and 7 once
        // WCR drops cartridge ROM to one wait. Expected values are hand-
        // derived from the model in cpu.v's header; the derivations sit
        // beside each assertion.
        restart();
        mark_n = 0;
        prog_h(16'h7800);                    // sei
        prog_h(16'hbcc0); prog_h(16'h0500);  // movhi -> r6 = 0x05000000
        prog_h(16'h4120);                    // mov 0, r9
        prog_h(16'hbd60); prog_h(16'h0200);  // movhi -> r11
        prog_h(16'ha16b); prog_h(16'h0024);  // movea -> r11 = 0x02000024
        prog_h(16'h4141);                    // mov 1, r10
        prog_h(16'hdcc6); prog_h(16'h0010);  // st.w r6, 0x10[r6]
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m0
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m1
        prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141);
        prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141);
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m2
        prog_h(16'hd54b); prog_h(16'h0000);  // st.h r10, 0[r11]: WCR ROM1W=1
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m3
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m4
        prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141);
        prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141);
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m5
        prog_h(16'h214a); prog_h(16'h214a); // mul r10, r10 x2
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m6
        prog_h(16'h254a);                    // div r10, r10
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m7
        prog_h(16'hcd46); prog_h(16'h0010);  // ld.w 0x10[r6], r10
        prog_h(16'hcd46); prog_h(16'h0010);  // ld.w again
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m8
        prog_h(16'h214a);                    // mul r10, r10
        prog_h(16'hcd46); prog_h(16'h0010);  // ld.w after a multiply
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m9
        prog_h(16'hd546); prog_h(16'h0030);  // st.h r10, 0x30[r6] x3
        prog_h(16'hd546); prog_h(16'h0030);
        prog_h(16'hd546); prog_h(16'h0030);
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m10
        prog_h(16'h8a02);                    // br +2: taken, to the next
        prog_h(16'h9a00);                    // nop: the never-taken branch
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m11
        prog_h(16'h6800); prog_h(16'h8bfe);  // hang
        go();
        wait_halt(30000, "t1");
        if (mark_n !== 12)
            $fatal(1, "t1: %0d markers, expected 12", mark_n);
        // marker pair at two waits: addImm max(1,3)=3, st.h max(1,6)+1=7
        expect_delta(1, 10, "t1 empty period, two-wait ROM");
        // eight 16-bit 1-cycle instructions, fetch-bound at 1+2 each
        expect_delta(2, 24 + 10, "t1 fetch-bound ALU, two waits");
        // marker pair at one wait: addImm max(1,2)=2, st.h max(1,4)+1=5
        expect_delta(4, 7, "t1 empty period, one-wait ROM");
        // the same eight instructions now cost 1+1 each
        expect_delta(5, 16 + 7, "t1 fetch-bound ALU, one wait");
        // MUL is 13, far above its 2-cycle fetch
        expect_delta(6, 26 + 7, "t1 multiply");
        // DIV is 38
        expect_delta(7, 38 + 7, "t1 divide");
        // ld.w: base 5 then 4 (after a load), fetch 4, one wait per
        // halfword access: max(5,4)+2 then max(4,4)+2
        expect_delta(8, 13 + 7, "t1 load pair");
        // a load straight after a multiply costs base 1: 13 + max(1,4)+2
        expect_delta(9, 19 + 7, "t1 load after multiply");
        // stores: 1, 1, then 4 for the third consecutive: max each with
        // fetch 4, plus one work RAM wait: 5+5+5
        expect_delta(10, 15 + 7, "t1 store streak");
        // taken branch 3, never-taken 1 under a 2-cycle fetch floor
        expect_delta(11, 5 + 7, "t1 branches");

        // The built images, run whole. Their own checks judge; the status
        // word carries the verdict and names the failing check on a spin.
        run_rom("cpu-alu", 2048, 200000);
        run_rom("cpu-branch", 1024, 200000);
        run_rom("busmap", 1024, 200000);
        run_rom("cpu-except", 1024, 200000);

        // The timer ROM's check phase, through the real timer and the
        // real interrupt path: its status 0x0000 write means every check
        // passed and the seconds display armed. The seconds themselves
        // are far too slow to simulate; the hardware run judges those.
        run_rom_status("timer", 1024, 16'h0000, 400000);

        // The pad ROM, through the real game pad and the real bus. Its
        // self-test publishes 0x600D only after the data registers came up
        // zero, a software read alone filled them, a hardware read reported
        // busy and finished, and the two agreed -- the one order that can
        // tell the two read paths apart, since they share a register.
        // Driving a second value afterwards proves the loop re-reads rather
        // than latching once.
        pad_buttons = 16'h1236;
        run_rom_status("pad", 1024, 16'h600d, 400000);
        wait_status(16'h1236, 400000, "pad");
        pad_buttons = 16'hc0de;
        wait_status(16'hc0de, 400000, "pad");
        if (pad_irq !== 1'b0)
            $fatal(1, "pad: the key interrupt fired on a report that sets SGN");

        $finish;
    end

    initial begin
        #30_000_000;
        $fatal(1, "timed out");
    end

endmodule
