`timescale 1ns/1ps
//
// Exercises the CPU against a behavioral memory implementing mem_bus's
// contract (answer the cycle after the access, holding between accesses), so
// a failure here points at the CPU rather than the bus. Two layers:
//
// Directed programs, hand-encoded halfwords generated by the repo's own
// assembler (scripts/lib/v810.ts, itself tested against beetle-vb's
// decoder), pin the machinery ROMs can't reach or can't distinguish: the
// documented reset state, system register quirks, TRAP/RETI round trips
// with the exact saved PC/PSW/ECR, zero-division and illegal-opcode entry,
// the duplexed and fatal escalations, and HALT against every interrupt
// acceptance condition -- ID, level masking, and the wake sequence.
//
// The completion scenarios (E1-E7, T2) cover the instruction groups issue
// #3 added: the extended four, CAXI, the FPU through the CPU with its
// exception codes and saved PCs, bitwise and search bit strings with the
// documented two-word read buffer, interrupts aborting DIV and landing
// inside strings, the instruction cache (a restored fabricated entry
// executing in place of ROM is the proof fetches really come from the
// arrays), and the charges for all of it.
//
// Then the built ROM images run to completion: each writes check numbers
// to WRAM 0x05000000 as it goes and 0x600D on success, so the bench
// reports the exact failing check when one spins. Build them first: a
// missing hex fails with a message, not silence.
//
// Programs load at the reset vector's trampoline (the same three halfwords
// the packer's jumpFar emits), so every run enters through the real reset
// path: PC 0xFFFFFFF0, mirrored into the top of the ROM.
//

module cpu_tb;

    localparam ROM_HWORDS   = 32768;    // 64KB, the directed-test ROM size
    localparam ROM_CAPACITY = 1048576;  // 2MB, the largest image built here
    localparam WRAM_HWORDS = 32768;

    reg clk = 1'b0;
    always #5 clk = ~clk;

    // Architectural time at the hardware's own 625/1248 ratio -- including
    // its two adjacent-clock enables per window, the tightest spacing the
    // per-CE machine ever sees -- so every drain and walk runs at a
    // realistic pace and the timing assertions below measure exactly what
    // the Pocket would.
    reg        ce = 1'b0;
    reg [10:0] ce_acc = 11'd0;
    always @(posedge clk) begin
        if (ce_acc + 11'd625 >= 11'd1248) begin
            ce_acc <= ce_acc + 11'd625 - 11'd1248;
            ce     <= 1'b1;
        end else begin
            ce_acc <= ce_acc + 11'd625;
            ce     <= 1'b0;
        end
    end

    reg reset_n = 1'b0;
    reg ready = 1'b1;
    reg irq_valid = 1'b0;
    reg [3:0] irq_level = 4'd0;

    wire        req, we;
    wire [26:1] a;
    wire [1:0]  be;
    wire [15:0] wd;
    reg  [15:0] rd;
    wire [31:0] dbg_pc;
    wire        dbg_halted;

    // The real timer answers region 2 and interrupts at level 1, wired
    // the way core_top wires it. The manual irq regs still drive the
    // directed scenarios, which never arm the timer; the two never
    // request at once.
    wire [15:0] timer_rdata;
    wire        timer_irq;

    timer u_timer (
        .clk(clk),
        .reset_n(reset_n),
        .ce(ce),
        .sel(req && a[26:24] == 3'd2),
        .addr(a),
        .we(we),
        .be(be),
        .wdata(wd),
        .rdata(timer_rdata),
        .irq(timer_irq)
    );

    // The real game pad answers the same region at its own registers and
    // interrupts at level 0, again wired the way core_top wires it. Its
    // report is driven straight from the bench, standing in for
    // host_pad_map, which src/tests/game_pad.v owns.
    reg  [15:0] pad_buttons = 16'h0002;
    wire [15:0] pad_rdata;
    wire        pad_irq;

    game_pad u_pad (
        .clk(clk),
        .reset_n(reset_n),
        .ce(ce),
        .sel(req && a[26:24] == 3'd2),
        .addr(a),
        .we(we),
        .be(be),
        .wdata(wd),
        .rdata(pad_rdata),
        .buttons(pad_buttons),
        .irq(pad_irq)
    );

    // A device that answers late. The VIP's memory and the cartridge in
    // SDRAM both hold ready down for several clocks per access, and that is
    // the case a two-halfword access gets wrong: the earlier half's answer
    // only sits on rdata for the first clock of the state that launches the
    // next request. Off unless a scenario turns it on, so every other
    // scenario keeps the timing it measures.
    reg        waits_on  = 1'b0;
    reg [2:0]  stall_cnt = 3'd0;
    reg [26:1] stall_a   = {26{1'b1}};
    wire       stall     = waits_on && stall_cnt != 3'd0;

    always @(posedge clk) begin
        if (!waits_on) begin
            stall_cnt <= 3'd0;
            stall_a   <= {26{1'b1}};
        end else if (req && a != stall_a) begin
            stall_a   <= a;          // a fresh access waits its turn
            stall_cnt <= 3'd3;
        end else if (stall_cnt != 3'd0) begin
            stall_cnt <= stall_cnt - 3'd1;
        end
    end

    reg rd_misc = 1'b0;   // last access hit region 2: the timer answers
    always @(posedge clk) if (req) rd_misc <= a[26:24] == 3'd2;

    // The region's two devices decode disjoint registers, so one answer is
    // the other's zero -- core_top merges them the same way.
    wire [15:0] misc_rdata = timer_rdata | pad_rdata;

    cpu dut (
        .clk(clk),
        .ce(ce),
        .reset_n(reset_n),
        .req(req),
        .addr(a),
        .we(we),
        .be(be),
        .wdata(wd),
        .rdata(rd_misc ? misc_rdata : rd),
        .ready(ready && !stall),
        .irq_valid(irq_valid || timer_irq || pad_irq),
        .irq_level(irq_valid ? irq_level : timer_irq ? 4'd1 : 4'd0),
        .dbg_pc(dbg_pc),
        .dbg_halted(dbg_halted)
    );

    // Behavioral memory: ROM in region 7 mirrored by rom_mask, work RAM in
    // region 5 mirrored by its size, zero from everything else. Writes into
    // region 0 are captured for the fatal-exception check. The answer lands
    // the cycle after the access and holds, like mem_bus.
    // Sized for the largest built image a run_rom can load, not for the
    // directed tests: the cartridge is in SDRAM now, so an image can be a
    // retail 2MB. ROM_HWORDS stays the directed tests' mask, which is what
    // puts their hand-written reset trampoline within reach of 0xFFFFFFF0.
    reg [15:0] rom  [0:ROM_CAPACITY-1];
    reg [15:0] wram [0:WRAM_HWORDS-1];
    reg [15:0] region0 [0:7];
    integer    rom_mask;
    reg [15:0] status;   // last halfword written to WRAM 0x05000000

    // Architectural-cycle timestamps of every status write: the timing
    // scenarios read cost differences straight off consecutive markers.
    integer ce_ticks = 0;
    integer marks [0:15];
    integer mark_n = 0;

    always @(posedge clk) begin
        if (ce) ce_ticks = ce_ticks + 1;
        if (req && we && a == 26'h2800000 && be[0]) begin
            if (mark_n < 16) marks[mark_n] = ce_ticks;
            mark_n = mark_n + 1;
        end
    end

    always @(posedge clk) begin
        if (req) begin
            if (we) begin
                case (a[26:24])
                    3'd5: begin
                        if (be[0]) wram[a[15:1]][7:0]  <= wd[7:0];
                        if (be[1]) wram[a[15:1]][15:8] <= wd[15:8];
                        if (a[23:1] == 23'd0) begin
                            if (be[0]) status[7:0]  <= wd[7:0];
                            if (be[1]) status[15:8] <= wd[15:8];
                        end
                    end
                    3'd0: if (a[23:1] < 23'd8) region0[a[3:1]] <= wd;
                    default: ;
                endcase
            end
            case (a[26:24])
                3'd7:    rd <= rom[a[26:1] & rom_mask];
                3'd5:    rd <= wram[a[15:1]];
                default: rd <= 16'd0;
            endcase
        end
    end

    // ------------------------------------------------------------------
    // Scenario plumbing
    // ------------------------------------------------------------------

    integer dp;   // deposit pointer, in halfword indexes
    integer gi;   // scenario loop index

    task automatic prog_h(input [15:0] value);
        begin
            rom[dp] = value;
            dp = dp + 1;
        end
    endtask

    // Hold reset and wipe the machine. The reset vector gets the packer's
    // jumpFar-to-0x07000000 trampoline; programs then deposit at index 0.
    task automatic restart;
        integer i;
        begin
            reset_n   = 1'b0;
            ready     = 1'b1;
            irq_valid = 1'b0;
            irq_level = 4'd0;
            for (i = 0; i < ROM_CAPACITY; i = i + 1) rom[i] = 16'hxxxx;
            for (i = 0; i < WRAM_HWORDS; i = i + 1) wram[i] = 16'hxxxx;
            for (i = 0; i < 8; i = i + 1) region0[i] = 16'hxxxx;
            status   = 16'hxxxx;
            rom_mask = ROM_HWORDS - 1;
            rom['h7FF8] = 16'hbc20;   // movhi 0x0700, r0, r1
            rom['h7FF9] = 16'h0700;
            rom['h7FFA] = 16'h1801;   // jmp [r1]
            dp = 0;
            @(negedge clk);
        end
    endtask

    task automatic go;
        begin
            repeat (4) @(negedge clk);
            reset_n = 1'b1;
        end
    endtask

    task automatic wait_halt(input integer max_cycles, input string what);
        integer i;
        begin
            i = 0;
            while (!dbg_halted) begin
                @(negedge clk);
                i = i + 1;
                if (i > max_cycles)
                    $fatal(1, "%0s: no halt after %0d cycles, pc %08x status %04x",
                           what, max_cycles, dbg_pc, status);
            end
        end
    endtask

    task automatic wait_wake(input integer max_cycles, input string what);
        integer i;
        begin
            i = 0;
            while (dbg_halted) begin
                @(negedge clk);
                i = i + 1;
                if (i > max_cycles)
                    $fatal(1, "%0s: still halted after %0d cycles", what, max_cycles);
            end
        end
    endtask

    task automatic expect_gpr(input integer n, input [31:0] expected,
                              input string what);
        if (dut.gpr[n] !== expected)
            $fatal(1, "%0s: r%0d is %08x, expected %08x",
                   what, n, dut.gpr[n], expected);
    endtask

    task automatic expect_delta(input integer idx, input integer expected,
                                input string what);
        if (marks[idx] - marks[idx-1] !== expected)
            $fatal(1, "%0s: markers %0d-%0d are %0d cycles apart, expected %0d",
                   what, idx - 1, idx, marks[idx] - marks[idx-1], expected);
    endtask

    // Runs a built ROM image to its success halt. The image's own checks do
    // the judging; the status word carries the verdict.
    task automatic run_rom(input string name, input integer hwords,
                           input integer max_cycles);
        integer fd;
        string  path;
        begin
            restart();
            path = {"../.roms/", name, ".hex"};
            fd = $fopen(path, "r");
            if (fd == 0)
                $fatal(1, "%0s: cannot open %0s; run pnpm run build:roms first",
                       name, path);
            $fclose(fd);
            $readmemh(path, rom);
            rom_mask = hwords - 1;
            go();
            wait_halt(max_cycles, name);
            if (status !== 16'h600d)
                $fatal(1, "%0s: halted with status %04x at pc %08x, expected 600d",
                       name, status, dbg_pc);
        end
    endtask

    // Runs a built ROM to a status value instead of a halt, for an image
    // whose pass is a running display rather than a stop.
    task automatic run_rom_status(input string name, input integer hwords,
                                  input [15:0] want,
                                  input integer max_cycles);
        integer fd;
        string  path;
        begin
            restart();
            path = {"../.roms/", name, ".hex"};
            fd = $fopen(path, "r");
            if (fd == 0)
                $fatal(1, "%0s: cannot open %0s; run pnpm run build:roms first",
                       name, path);
            $fclose(fd);
            $readmemh(path, rom);
            rom_mask = hwords - 1;
            go();
            wait_status(want, max_cycles, name);
        end
    endtask

    // Waits for a running image to publish a status word, for a ROM whose
    // display loop answers more than once.
    task automatic wait_status(input [15:0] want, input integer max_cycles,
                               input string name);
        integer i;
        begin
            i = 0;
            while (status !== want) begin
                @(negedge clk);
                i = i + 1;
                if (i > max_cycles)
                    $fatal(1, "%0s: status %04x never became %04x in %0d cycles, pc %08x",
                           name, status, want, max_cycles, dbg_pc);
            end
        end
    endtask

    // ------------------------------------------------------------------
    // The scenarios
    // ------------------------------------------------------------------

    initial begin
        // D1: reset state, observed architecturally. The first fetch goes to
        // 0xFFFFFFF0 with the top five bits already gone, and the read-only
        // system registers carry their fixed values.
        restart();
        prog_h(16'h7545);  // stsr PSW,  r10
        prog_h(16'h7564);  // stsr ECR,  r11
        prog_h(16'h7586);  // stsr PIR,  r12
        prog_h(16'h75a7);  // stsr TKCW, r13
        prog_h(16'h75de);  // stsr 30,   r14
        prog_h(16'h75e8);  // stsr 8,    r15
        prog_h(16'h6800);  // halt
        ready = 1'b0;
        go();
        while (!req) @(negedge clk);
        if (a !== 26'h3FFFFF8)
            $fatal(1, "d1: first fetch at %07x, expected 3fffff8 (0xFFFFFFF0 masked)", a);
        repeat (5) begin
            @(negedge clk);
            if (!req || a !== 26'h3FFFFF8)
                $fatal(1, "d1: fetch changed while ready was low");
        end
        ready = 1'b1;
        wait_halt(2000, "d1");
        expect_gpr(10, 32'h0000_8000, "d1 PSW");
        expect_gpr(11, 32'h0000_FFF0, "d1 ECR");
        expect_gpr(12, 32'h0000_5346, "d1 PIR");
        expect_gpr(13, 32'h0000_00E0, "d1 TKCW");
        expect_gpr(14, 32'h0000_0004, "d1 sysreg 30");
        expect_gpr(15, 32'h0000_0000, "d1 reserved sysreg");

        // D2: system register quirks: register 31 reads back the absolute
        // value, ECR ignores LDSR, 29 is plain storage, PSW round-trips
        // through its mask.
        restart();
        prog_h(16'ha140); prog_h(16'hfff8);  // movea 0xFFF8, r0, r10 (-8)
        prog_h(16'h715f);                    // ldsr r10, 31
        prog_h(16'h757f);                    // stsr 31, r11
        prog_h(16'h7144);                    // ldsr r10, ECR
        prog_h(16'h7584);                    // stsr ECR, r12
        prog_h(16'h715d);                    // ldsr r10, 29
        prog_h(16'h75bd);                    // stsr 29, r13
        prog_h(16'hbdc0); prog_h(16'h0003);  // movhi 3, r0, r14
        prog_h(16'ha1ce); prog_h(16'h0009);  // movea 9, r14, r14
        prog_h(16'h71c5);                    // ldsr r14, PSW
        prog_h(16'h75e5);                    // stsr PSW, r15
        prog_h(16'h6800);                    // halt
        go();
        wait_halt(3000, "d2");
        expect_gpr(11, 32'h0000_0008, "d2 sysreg 31 abs");
        expect_gpr(12, 32'h0000_FFF0, "d2 ECR ldsr ignored");
        expect_gpr(13, 32'hFFFF_FFF8, "d2 sysreg 29");
        expect_gpr(15, 32'h0003_0009, "d2 PSW roundtrip");

        // D3: TRAP through both vector halves, RETI resuming, and the saved
        // PC/PSW/ECR checked from inside the handler.
        restart();
        prog_h(16'h4140);  // 00: mov 0, r10
        prog_h(16'h7145);  // 02: ldsr r10, PSW      (clear reset's NP)
        prog_h(16'h6003);  // 04: trap 3             -> 0xFFFFFFA0, code FFA3
        prog_h(16'h4201);  // 06: mov 1, r16
        prog_h(16'h6013);  // 08: trap 19            -> 0xFFFFFFB0, code FFB3
        prog_h(16'h41e2);  // 0A: mov 2, r15
        prog_h(16'h6800);  // 0C: halt
        dp = 'h7FD0;       // handler 0xFFFFFFA0
        prog_h(16'h7540);  // stsr EIPC,  r10
        prog_h(16'h7561);  // stsr EIPSW, r11
        prog_h(16'h7584);  // stsr ECR,   r12
        prog_h(16'h75a5);  // stsr PSW,   r13
        prog_h(16'h6400);  // reti
        dp = 'h7FD8;       // handler 0xFFFFFFB0
        prog_h(16'h75c4);  // stsr ECR, r14
        prog_h(16'h6400);  // reti
        go();
        wait_halt(4000, "d3");
        expect_gpr(10, 32'h0700_0006, "d3 EIPC (trap saves next PC)");
        expect_gpr(11, 32'h0000_0000, "d3 EIPSW");
        expect_gpr(12, 32'h0000_FFA3, "d3 ECR after trap 3");
        expect_gpr(13, 32'h0000_5000, "d3 PSW in handler (EP|ID)");
        expect_gpr(14, 32'h0000_FFB3, "d3 ECR after trap 19");
        expect_gpr(16, 32'h0000_0001, "d3 resumed after reti");
        expect_gpr(15, 32'h0000_0002, "d3 resumed after second reti");

        // D4a: divide by zero: reg2 untouched, restore PC is the divide
        // itself, so the handler halts rather than retrying forever.
        restart();
        prog_h(16'h4140);  // 00: mov 0, r10
        prog_h(16'h7145);  // 02: ldsr r10, PSW
        prog_h(16'h4145);  // 04: mov 5, r10
        prog_h(16'h4160);  // 06: mov 0, r11
        prog_h(16'h254b);  // 08: div r11, r10
        prog_h(16'h6800);  // 0A: halt
        dp = 'h7FC0;       // handler 0xFFFFFF80
        prog_h(16'h7584);  // stsr ECR,  r12
        prog_h(16'h75a0);  // stsr EIPC, r13
        prog_h(16'h6800);  // halt
        go();
        wait_halt(3000, "d4a");
        expect_gpr(10, 32'h0000_0005, "d4a reg2 untouched");
        expect_gpr(12, 32'h0000_FF80, "d4a ECR");
        expect_gpr(13, 32'h0700_0008, "d4a EIPC is the divide itself");

        // D4b: an invalid opcode (0x1B) raises illegal-opcode with the
        // faulting address saved.
        restart();
        prog_h(16'h4140);  // 00: mov 0, r10
        prog_h(16'h7145);  // 02: ldsr r10, PSW
        prog_h(16'h6c00);  // 04: opcode 0x1B, invalid
        prog_h(16'h6800);  // 06: halt
        dp = 'h7FC8;       // handler 0xFFFFFF90
        prog_h(16'h7584);  // stsr ECR,  r12
        prog_h(16'h75a0);  // stsr EIPC, r13
        prog_h(16'h6800);  // halt
        go();
        wait_halt(3000, "d4b");
        expect_gpr(12, 32'h0000_FF90, "d4b ECR");
        expect_gpr(13, 32'h0700_0004, "d4b EIPC is the illegal opcode");

        // D5: a trap inside a handler duplexes: FEPC pair, ECR's high half,
        // NP set, handler 0xFFFFFFD0.
        restart();
        prog_h(16'h4140);  // 00: mov 0, r10
        prog_h(16'h7145);  // 02: ldsr r10, PSW
        prog_h(16'h6000);  // 04: trap 0
        prog_h(16'h6800);  // 06: halt
        dp = 'h7FD0;       // handler 0xFFFFFFA0
        prog_h(16'h6001);  // trap 1 with EP set -> duplexed
        dp = 'h7FE8;       // handler 0xFFFFFFD0
        prog_h(16'h7584);  // stsr ECR,  r12
        prog_h(16'h75a2);  // stsr FEPC, r13
        prog_h(16'h75c5);  // stsr PSW,  r14
        prog_h(16'h6800);  // halt
        go();
        wait_halt(3000, "d5");
        expect_gpr(12, 32'hFFA1_FFA0, "d5 ECR carries both codes");
        expect_gpr(13, 32'hFFFF_FFA2, "d5 FEPC");
        expect_gpr(14, 32'h0000_D000, "d5 PSW (NP|EP|ID)");

        // D6: an exception with NP still set from reset is fatal: the cause
        // word, PSW and PC land at 0x0/0x4/0x8 and the CPU stops for good.
        restart();
        prog_h(16'h6000);  // 00: trap 0, NP set -> fatal
        go();
        wait_halt(3000, "d6");
        // the behavioral memory commits a write the clock after its req;
        // let the last fatal write land before reading it back
        repeat (2) @(negedge clk);
        if ({region0[1], region0[0]} !== 32'hFFFF_FFA0)
            $fatal(1, "d6: fatal cause word is %04x%04x, expected ffffffa0",
                   region0[1], region0[0]);
        if ({region0[3], region0[2]} !== 32'h0000_8000)
            $fatal(1, "d6: fatal PSW is %04x%04x, expected 00008000",
                   region0[3], region0[2]);
        if ({region0[5], region0[4]} !== 32'h0700_0002)
            $fatal(1, "d6: fatal PC is %04x%04x, expected 07000002",
                   region0[5], region0[4]);
        repeat (50) @(negedge clk);
        if (!dbg_halted) $fatal(1, "d6: fatal halt did not hold");

        // D7: HALT wakes on an accepted interrupt: entry saves the address
        // after the halt, raises the level, and RETI resumes there.
        restart();
        prog_h(16'h4140);  // 00: mov 0, r10
        prog_h(16'h7145);  // 02: ldsr r10, PSW
        prog_h(16'h6800);  // 04: halt
        prog_h(16'h4147);  // 06: mov 7, r10
        prog_h(16'h6800);  // 08: halt
        dp = 'h7F10;       // handler 0xFFFFFE20 (level 2)
        prog_h(16'h7564);  // stsr ECR,  r11
        prog_h(16'h7585);  // stsr PSW,  r12
        prog_h(16'h75a0);  // stsr EIPC, r13
        prog_h(16'h6400);  // reti
        go();
        wait_halt(2000, "d7 first halt");
        @(negedge clk);
        irq_level = 4'd2;
        irq_valid = 1'b1;
        wait_wake(1000, "d7 wake");
        irq_valid = 1'b0;
        wait_halt(3000, "d7 second halt");
        expect_gpr(10, 32'h0000_0007, "d7 resumed after reti");
        expect_gpr(11, 32'h0000_FE20, "d7 ECR");
        expect_gpr(12, 32'h0003_5000, "d7 PSW in handler (EP|ID|I=3)");
        expect_gpr(13, 32'h0700_0006, "d7 EIPC is the instruction after halt");

        // D8: the level mask: I=3 blocks level 2 and accepts level 3, and
        // acceptance raises I to level+1.
        restart();
        prog_h(16'hbd40); prog_h(16'h0003);  // movhi 3, r0, r10
        prog_h(16'h7145);  // 04: ldsr r10, PSW      (I=3, everything else 0)
        prog_h(16'h6800);  // 06: halt
        prog_h(16'h4149);  // 08: mov 9, r10
        prog_h(16'h6800);  // 0A: halt
        dp = 'h7F18;       // handler 0xFFFFFE30 (level 3)
        prog_h(16'h7565);  // stsr PSW, r11
        prog_h(16'h6400);  // reti
        go();
        wait_halt(2000, "d8 halt");
        @(negedge clk);
        irq_level = 4'd2;
        irq_valid = 1'b1;
        repeat (600) @(negedge clk);
        if (!dbg_halted)
            $fatal(1, "d8: level 2 woke a CPU masked at I=3");
        irq_level = 4'd3;
        wait_wake(1000, "d8 wake at level 3");
        irq_valid = 1'b0;
        wait_halt(3000, "d8 second halt");
        expect_gpr(10, 32'h0000_0009, "d8 resumed");
        expect_gpr(11, 32'h0004_5000, "d8 PSW in handler (EP|ID|I=4)");

        // D9: ID masks everything: a halt behind SEI never wakes, and that
        // is correct behavior rather than a hang.
        restart();
        prog_h(16'h4140);  // 00: mov 0, r10
        prog_h(16'h7145);  // 02: ldsr r10, PSW
        prog_h(16'h7800);  // 04: sei
        prog_h(16'h6800);  // 06: halt
        go();
        wait_halt(2000, "d9 halt");
        @(negedge clk);
        irq_level = 4'd3;
        irq_valid = 1'b1;
        repeat (900) @(negedge clk);
        if (!dbg_halted)
            $fatal(1, "d9: an interrupt woke a halt behind SEI");
        irq_valid = 1'b0;

        // T1: the cost model, measured. Each status write is a marker; the
        // difference between consecutive markers in architectural cycles is
        // the exact charge of the instructions between them. A marker pair
        // (addImm + stH) costs 10 cycles at the reset wait states (fetch-
        // bound: 3 for the addImm, max(1, 2x3)+1 for the store) and 7 once
        // WCR drops cartridge ROM to one wait. Expected values are hand-
        // derived from the model in cpu.v's header; the derivations sit
        // beside each assertion.
        restart();
        mark_n = 0;
        prog_h(16'h7800);                    // sei
        prog_h(16'hbcc0); prog_h(16'h0500);  // movhi -> r6 = 0x05000000
        prog_h(16'h4120);                    // mov 0, r9
        prog_h(16'hbd60); prog_h(16'h0200);  // movhi -> r11
        prog_h(16'ha16b); prog_h(16'h0024);  // movea -> r11 = 0x02000024
        prog_h(16'h4141);                    // mov 1, r10
        prog_h(16'hdcc6); prog_h(16'h0010);  // st.w r6, 0x10[r6]
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m0
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m1
        prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141);
        prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141);
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m2
        prog_h(16'hd54b); prog_h(16'h0000);  // st.h r10, 0[r11]: WCR ROM1W=1
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m3
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m4
        prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141);
        prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141); prog_h(16'h4141);
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m5
        prog_h(16'h214a); prog_h(16'h214a); // mul r10, r10 x2
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m6
        prog_h(16'h254a);                    // div r10, r10
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m7
        prog_h(16'hcd46); prog_h(16'h0010);  // ld.w 0x10[r6], r10
        prog_h(16'hcd46); prog_h(16'h0010);  // ld.w again
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m8
        prog_h(16'h214a);                    // mul r10, r10
        prog_h(16'hcd46); prog_h(16'h0010);  // ld.w after a multiply
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m9
        prog_h(16'hd546); prog_h(16'h0030);  // st.h r10, 0x30[r6] x3
        prog_h(16'hd546); prog_h(16'h0030);
        prog_h(16'hd546); prog_h(16'h0030);
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m10
        prog_h(16'h8a02);                    // br +2: taken, to the next
        prog_h(16'h9a00);                    // nop: the never-taken branch
        prog_h(16'h4521); prog_h(16'hd526); prog_h(16'h0000);  // m11
        prog_h(16'h6800); prog_h(16'h8bfe);  // hang
        go();
        wait_halt(30000, "t1");
        if (mark_n !== 12)
            $fatal(1, "t1: %0d markers, expected 12", mark_n);
        // marker pair at two waits: addImm max(1,3)=3, st.h max(1,6)+1=7
        expect_delta(1, 10, "t1 empty period, two-wait ROM");
        // eight 16-bit 1-cycle instructions, fetch-bound at 1+2 each
        expect_delta(2, 24 + 10, "t1 fetch-bound ALU, two waits");
        // marker pair at one wait: addImm max(1,2)=2, st.h max(1,4)+1=5
        expect_delta(4, 7, "t1 empty period, one-wait ROM");
        // the same eight instructions now cost 1+1 each
        expect_delta(5, 16 + 7, "t1 fetch-bound ALU, one wait");
        // MUL is 13, far above its 2-cycle fetch
        expect_delta(6, 26 + 7, "t1 multiply");
        // DIV is 38
        expect_delta(7, 38 + 7, "t1 divide");
        // ld.w: base 5 then 4 (after a load), fetch 4, one wait per
        // halfword access: max(5,4)+2 then max(4,4)+2
        expect_delta(8, 13 + 7, "t1 load pair");
        // a load straight after a multiply costs base 1: 13 + max(1,4)+2
        expect_delta(9, 19 + 7, "t1 load after multiply");
        // stores: 1, 1, then 4 for the third consecutive: max each with
        // fetch 4, plus one work RAM wait: 5+5+5
        expect_delta(10, 15 + 7, "t1 store streak");
        // taken branch 3, never-taken 1 under a 2-cycle fetch floor
        expect_delta(11, 5 + 7, "t1 branches");


        // ------------------------------------------------------------------
        // The completion scenarios: floating point, bit strings, CAXI, the
        // extended four, the instruction cache, and long-instruction
        // interruption. Programs are assembled by scripts/lib/v810.ts (the
        // generator lives with the session notes); expected values are
        // hand-derived from the scroll, the V810 manual and beetle-vb, per
        // the citations in cpu.v.
        // ------------------------------------------------------------------

        // E1: XB, XH, REV and MPYHW compute the documented results and
        // leave every PSW flag alone.
        restart();
        prog_h(16'h4140);  // 07000000
        prog_h(16'h7145);  // 07000002
        prog_h(16'h7800);  // 07000004
        prog_h(16'hbd40);  // 07000006
        prog_h(16'h1234);  // 07000008
        prog_h(16'ha14a);  // 0700000a
        prog_h(16'h5678);  // 0700000c
        prog_h(16'hf940);  // 0700000e
        prog_h(16'h2000);  // 07000010
        prog_h(16'hbd60);  // 07000012
        prog_h(16'h1234);  // 07000014
        prog_h(16'ha16b);  // 07000016
        prog_h(16'h5678);  // 07000018
        prog_h(16'hf960);  // 0700001a
        prog_h(16'h2400);  // 0700001c
        prog_h(16'hbd80);  // 0700001e
        prog_h(16'h1234);  // 07000020
        prog_h(16'ha18c);  // 07000022
        prog_h(16'h5678);  // 07000024
        prog_h(16'hf9ac);  // 07000026
        prog_h(16'h2800);  // 07000028
        prog_h(16'ha1c0);  // 0700002a
        prog_h(16'h03e8);  // 0700002c
        prog_h(16'hbde0);  // 0700002e
        prog_h(16'h0002);  // 07000030
        prog_h(16'ha1ef);  // 07000032
        prog_h(16'hffff);  // 07000034
        prog_h(16'hf9cf);  // 07000036
        prog_h(16'h3000);  // 07000038
        prog_h(16'h421f);  // 0700003a
        prog_h(16'h4221);  // 0700003c
        prog_h(16'h0611);  // 0700003e
        prog_h(16'hbe40);  // 07000040
        prog_h(16'h1234);  // 07000042
        prog_h(16'ha252);  // 07000044
        prog_h(16'h5678);  // 07000046
        prog_h(16'hfa40);  // 07000048
        prog_h(16'h2000);  // 0700004a
        prog_h(16'hfa40);  // 0700004c
        prog_h(16'h2400);  // 0700004e
        prog_h(16'hfa52);  // 07000050
        prog_h(16'h2800);  // 07000052
        prog_h(16'hfa51);  // 07000054
        prog_h(16'h3000);  // 07000056
        prog_h(16'h7665);  // 07000058
        prog_h(16'h6800);  // 0700005a
        go();
        wait_halt(4000, "e1");
        expect_gpr(10, 32'h1234_7856, "e1 xb swaps the low bytes");
        expect_gpr(11, 32'h5678_1234, "e1 xh swaps the halfwords");
        expect_gpr(13, 32'h1E6A_2C48, "e1 rev mirrors the bits");
        expect_gpr(14, 32'hFFFF_FC18, "e1 mpyhw sign-extends 17 bits");
        expect_gpr(19, 32'h0000_1009, "e1 none of the four touch a flag");

        // E2: CAXI compares like CMP and writes either way: the exchange
        // value on a match, the fetched word back on a mismatch.
        restart();
        prog_h(16'h4140);  // 07000000
        prog_h(16'h7145);  // 07000002
        prog_h(16'h7800);  // 07000004
        prog_h(16'hbcc0);  // 07000006
        prog_h(16'h0500);  // 07000008
        prog_h(16'hbd40);  // 0700000a
        prog_h(16'h1111);  // 0700000c
        prog_h(16'ha14a);  // 0700000e
        prog_h(16'h2222);  // 07000010
        prog_h(16'hdd46);  // 07000012
        prog_h(16'h0100);  // 07000014
        prog_h(16'hbfc0);  // 07000016
        prog_h(16'h3333);  // 07000018
        prog_h(16'ha3de);  // 0700001a
        prog_h(16'h4444);  // 0700001c
        prog_h(16'he946);  // 0700001e
        prog_h(16'h0100);  // 07000020
        prog_h(16'h4962);  // 07000022
        prog_h(16'hcd86);  // 07000024
        prog_h(16'h0100);  // 07000026
        prog_h(16'hbda0);  // 07000028
        prog_h(16'h5555);  // 0700002a
        prog_h(16'ha1ad);  // 0700002c
        prog_h(16'h5555);  // 0700002e
        prog_h(16'he9a6);  // 07000030
        prog_h(16'h0100);  // 07000032
        prog_h(16'h49c2);  // 07000034
        prog_h(16'h49e1);  // 07000036
        prog_h(16'hce06);  // 07000038
        prog_h(16'h0100);  // 0700003a
        prog_h(16'hbe20);  // 0700003c
        prog_h(16'h1111);  // 0700003e
        prog_h(16'ha231);  // 07000040
        prog_h(16'h1111);  // 07000042
        prog_h(16'hea26);  // 07000044
        prog_h(16'h0100);  // 07000046
        prog_h(16'h4a41);  // 07000048
        prog_h(16'h6800);  // 0700004a
        go();
        wait_halt(6000, "e2");
        expect_gpr(11, 32'h0000_0001, "e2 match sets Z");
        expect_gpr(12, 32'h3333_4444, "e2 match stored the exchange value");
        expect_gpr(14, 32'h0000_0000, "e2 mismatch clears Z");
        expect_gpr(15, 32'h0000_0000, "e2 greater compare leaves CY clear");
        expect_gpr(16, 32'h3333_4444, "e2 mismatch left memory alone");
        expect_gpr(13, 32'h3333_4444, "e2 mismatch loaded reg2 with the word");
        expect_gpr(17, 32'h3333_4444, "e2 lower mismatch loads reg2 too");
        expect_gpr(18, 32'h0000_0001, "e2 the borrow sets CY");

        // E3: the FPU through the CPU: conversions and arithmetic write
        // reg2, FZD and FRO kill their result and vector through 0xFFFFFF60
        // with the faulting instruction saved and the status flag latched
        // before entry.
        restart();
        prog_h(16'ha800);  // 07000000
        prog_h(16'h0020);  // 07000002
        prog_h(16'h4e60);  // 07000004
        prog_h(16'h940a);  // 07000006
        prog_h(16'h7684);  // 07000008
        prog_h(16'h76a0);  // 0700000a
        prog_h(16'h76c5);  // 0700000c
        prog_h(16'h8a08);  // 0700000e
        prog_h(16'h7724);  // 07000010
        prog_h(16'h7740);  // 07000012
        prog_h(16'h7765);  // 07000014
        prog_h(16'h4661);  // 07000016
        prog_h(16'h7540);  // 07000018
        prog_h(16'h4544);  // 0700001a
        prog_h(16'h7140);  // 0700001c
        prog_h(16'h6400);  // 0700001e
        prog_h(16'h4140);  // 07000020
        prog_h(16'h7145);  // 07000022
        prog_h(16'h7800);  // 07000024
        prog_h(16'h4260);  // 07000026
        prog_h(16'h4165);  // 07000028
        prog_h(16'hf98b);  // 0700002a
        prog_h(16'h0800);  // 0700002c
        prog_h(16'hbda0);  // 0700002e
        prog_h(16'h3f80);  // 07000030
        prog_h(16'hbdc0);  // 07000032
        prog_h(16'h4000);  // 07000034
        prog_h(16'hf9ae);  // 07000036
        prog_h(16'h1000);  // 07000038
        prog_h(16'hf9ec);  // 0700003a
        prog_h(16'h0c00);  // 0700003c
        prog_h(16'hbe00);  // 0700003e
        prog_h(16'h40a0);  // 07000040
        prog_h(16'h4220);  // 07000042
        prog_h(16'hfa11);  // 07000044
        prog_h(16'h1c00);  // 07000046
        prog_h(16'hbe40);  // 07000048
        prog_h(16'h7fc0);  // 0700004a
        prog_h(16'hf9b2);  // 0700004c
        prog_h(16'h1000);  // 0700004e
        prog_h(16'h7785);  // 07000050
        prog_h(16'h6800);  // 07000052
        dp = 'h7FB0;   // handler 0xFFFFFF60
        prog_h(16'hbc20); prog_h(16'h0700);
        prog_h(16'ha021); prog_h(16'h0004);
        prog_h(16'h1801);
        go();
        wait_halt(8000, "e3");
        expect_gpr(12, 32'h40A0_0000, "e3 cvt.ws 5");
        expect_gpr(13, 32'h4040_0000, "e3 addf 1+2, NaN add killed");
        expect_gpr(15, 32'h0000_0005, "e3 cvt.sw back");
        expect_gpr(16, 32'h40A0_0000, "e3 divf by zero left reg2 alone");
        expect_gpr(19, 32'h0000_0002, "e3 both exceptions vectored");
        expect_gpr(20, 32'h0000_FF68, "e3 FZD code");
        expect_gpr(21, 32'h0700_0044, "e3 FZD saves the divf itself");
        expect_gpr(22, 32'h0000_5081, "e3 FZD flag set before entry");
        expect_gpr(25, 32'h0000_FF60, "e3 FRO code");
        expect_gpr(26, 32'h0700_004C, "e3 FRO saves the addf itself");
        expect_gpr(27, 32'h0000_5280, "e3 FRO joins the sticky FZD");
        expect_gpr(28, 32'h0000_1280, "e3 the FP flags survive RETI");

        // E4: bitwise bit strings across words and offsets, and the length
        // zero invocation that only masks the registers.
        restart();
        prog_h(16'h4140);  // 07000000
        prog_h(16'h7145);  // 07000002
        prog_h(16'h7800);  // 07000004
        prog_h(16'hbcc0);  // 07000006
        prog_h(16'h0500);  // 07000008
        prog_h(16'hbd40);  // 0700000a
        prog_h(16'hf0f1);  // 0700000c
        prog_h(16'ha14a);  // 0700000e
        prog_h(16'hf0f0);  // 07000010
        prog_h(16'hdd46);  // 07000012
        prog_h(16'h0200);  // 07000014
        prog_h(16'hbd40);  // 07000016
        prog_h(16'h0001);  // 07000018
        prog_h(16'ha14a);  // 0700001a
        prog_h(16'haaaa);  // 0700001c
        prog_h(16'hdd46);  // 0700001e
        prog_h(16'h0204);  // 07000020
        prog_h(16'hbd40);  // 07000022
        prog_h(16'h1111);  // 07000024
        prog_h(16'ha14a);  // 07000026
        prog_h(16'h1111);  // 07000028
        prog_h(16'hdd46);  // 0700002a
        prog_h(16'h0300);  // 0700002c
        prog_h(16'hbd40);  // 0700002e
        prog_h(16'h2222);  // 07000030
        prog_h(16'ha14a);  // 07000032
        prog_h(16'h2222);  // 07000034
        prog_h(16'hdd46);  // 07000036
        prog_h(16'h0304);  // 07000038
        prog_h(16'hbd40);  // 0700003a
        prog_h(16'h3333);  // 0700003c
        prog_h(16'ha14a);  // 0700003e
        prog_h(16'h3333);  // 07000040
        prog_h(16'hdd46);  // 07000042
        prog_h(16'h0308);  // 07000044
        prog_h(16'h4340);  // 07000046
        prog_h(16'h4360);  // 07000048
        prog_h(16'ha380);  // 0700004a
        prog_h(16'h0030);  // 0700004c
        prog_h(16'hbfa0);  // 0700004e
        prog_h(16'h0500);  // 07000050
        prog_h(16'ha3bd);  // 07000052
        prog_h(16'h0300);  // 07000054
        prog_h(16'hbfc0);  // 07000056
        prog_h(16'h0500);  // 07000058
        prog_h(16'ha3de);  // 0700005a
        prog_h(16'h0200);  // 0700005c
        prog_h(16'h7c0b);  // 0700005e
        prog_h(16'hcd66);  // 07000060
        prog_h(16'h0300);  // 07000062
        prog_h(16'hcd86);  // 07000064
        prog_h(16'h0304);  // 07000066
        prog_h(16'h01ba);  // 07000068
        prog_h(16'h01db);  // 0700006a
        prog_h(16'h01fc);  // 0700006c
        prog_h(16'h021d);  // 0700006e
        prog_h(16'h023e);  // 07000070
        prog_h(16'h4348);  // 07000072
        prog_h(16'h4364);  // 07000074
        prog_h(16'h438c);  // 07000076
        prog_h(16'hbfa0);  // 07000078
        prog_h(16'h0500);  // 0700007a
        prog_h(16'ha3bd);  // 0700007c
        prog_h(16'h0308);  // 0700007e
        prog_h(16'hbfc0);  // 07000080
        prog_h(16'h0500);  // 07000082
        prog_h(16'ha3de);  // 07000084
        prog_h(16'h0200);  // 07000086
        prog_h(16'h7c0a);  // 07000088
        prog_h(16'hce46);  // 0700008a
        prog_h(16'h0308);  // 0700008c
        prog_h(16'ha340);  // 0700008e
        prog_h(16'hffff);  // 07000090
        prog_h(16'hbf60);  // 07000092
        prog_h(16'heeef);  // 07000094
        prog_h(16'ha37b);  // 07000096
        prog_h(16'heeee);  // 07000098
        prog_h(16'h4380);  // 0700009a
        prog_h(16'hbfa0);  // 0700009c
        prog_h(16'h0500);  // 0700009e
        prog_h(16'ha3bd);  // 070000a0
        prog_h(16'h0303);  // 070000a2
        prog_h(16'hbfc0);  // 070000a4
        prog_h(16'h0500);  // 070000a6
        prog_h(16'ha3de);  // 070000a8
        prog_h(16'h0202);  // 070000aa
        prog_h(16'h7c0b);  // 070000ac
        prog_h(16'h027a);  // 070000ae
        prog_h(16'h029b);  // 070000b0
        prog_h(16'h02bd);  // 070000b2
        prog_h(16'h02de);  // 070000b4
        prog_h(16'h6800);  // 070000b6
        go();
        wait_halt(12000, "e4");
        expect_gpr(11, 32'hF0F0_F0F0, "e4 aligned word moved");
        expect_gpr(12, 32'h2222_AAAA, "e4 partial tail merged");
        expect_gpr(13, 32'd16, "e4 r26 ends at the next free bit");
        expect_gpr(14, 32'd16, "e4 r27 likewise");
        expect_gpr(15, 32'd0, "e4 r28 drained");
        expect_gpr(16, 32'h0500_0304, "e4 r29 on the tail word");
        expect_gpr(17, 32'h0500_0204, "e4 r30 past the consumed word");
        expect_gpr(18, 32'h333C_3C33, "e4 offset xor merged");
        expect_gpr(19, 32'd31, "e4 length zero masks r26");
        expect_gpr(20, 32'd14, "e4 length zero masks r27");
        expect_gpr(21, 32'h0500_0300, "e4 length zero masks r29");
        expect_gpr(22, 32'h0500_0200, "e4 length zero masks r30");

        // E4b: the read-buffer artifact. A destination 32 bits after the
        // source copies cleanly -- 64 bits of buffering covers it -- and a
        // destination 64 bits after corrupts the third word, exactly as
        // documented [Scroll, CPU > Bit Strings > Bitwise].
        restart();
        prog_h(16'h4140);  // 07000000
        prog_h(16'h7145);  // 07000002
        prog_h(16'h7800);  // 07000004
        prog_h(16'hbcc0);  // 07000006
        prog_h(16'h0500);  // 07000008
        prog_h(16'hbd40);  // 0700000a
        prog_h(16'hdeae);  // 0700000c
        prog_h(16'ha14a);  // 0700000e
        prog_h(16'hbeef);  // 07000010
        prog_h(16'hdd46);  // 07000012
        prog_h(16'h0400);  // 07000014
        prog_h(16'hbd40);  // 07000016
        prog_h(16'hcaff);  // 07000018
        prog_h(16'ha14a);  // 0700001a
        prog_h(16'hf00d);  // 0700001c
        prog_h(16'hdd46);  // 0700001e
        prog_h(16'h0404);  // 07000020
        prog_h(16'hbd40);  // 07000022
        prog_h(16'h999a);  // 07000024
        prog_h(16'ha14a);  // 07000026
        prog_h(16'h9999);  // 07000028
        prog_h(16'hdd46);  // 0700002a
        prog_h(16'h0408);  // 0700002c
        prog_h(16'h4340);  // 0700002e
        prog_h(16'h4360);  // 07000030
        prog_h(16'ha380);  // 07000032
        prog_h(16'h0040);  // 07000034
        prog_h(16'hbfa0);  // 07000036
        prog_h(16'h0500);  // 07000038
        prog_h(16'ha3bd);  // 0700003a
        prog_h(16'h0404);  // 0700003c
        prog_h(16'hbfc0);  // 0700003e
        prog_h(16'h0500);  // 07000040
        prog_h(16'ha3de);  // 07000042
        prog_h(16'h0400);  // 07000044
        prog_h(16'h7c0b);  // 07000046
        prog_h(16'hcd66);  // 07000048
        prog_h(16'h0404);  // 0700004a
        prog_h(16'hcd86);  // 0700004c
        prog_h(16'h0408);  // 0700004e
        prog_h(16'hbd40);  // 07000050
        prog_h(16'hdeae);  // 07000052
        prog_h(16'ha14a);  // 07000054
        prog_h(16'hbeef);  // 07000056
        prog_h(16'hdd46);  // 07000058
        prog_h(16'h0500);  // 0700005a
        prog_h(16'hbd40);  // 0700005c
        prog_h(16'hcaff);  // 0700005e
        prog_h(16'ha14a);  // 07000060
        prog_h(16'hf00d);  // 07000062
        prog_h(16'hdd46);  // 07000064
        prog_h(16'h0504);  // 07000066
        prog_h(16'hbd40);  // 07000068
        prog_h(16'h999a);  // 0700006a
        prog_h(16'ha14a);  // 0700006c
        prog_h(16'h9999);  // 0700006e
        prog_h(16'hdd46);  // 07000070
        prog_h(16'h0508);  // 07000072
        prog_h(16'hbd40);  // 07000074
        prog_h(16'h5555);  // 07000076
        prog_h(16'ha14a);  // 07000078
        prog_h(16'h5555);  // 0700007a
        prog_h(16'hdd46);  // 0700007c
        prog_h(16'h050c);  // 0700007e
        prog_h(16'hdd46);  // 07000080
        prog_h(16'h0510);  // 07000082
        prog_h(16'h4340);  // 07000084
        prog_h(16'h4360);  // 07000086
        prog_h(16'ha380);  // 07000088
        prog_h(16'h0060);  // 0700008a
        prog_h(16'hbfa0);  // 0700008c
        prog_h(16'h0500);  // 0700008e
        prog_h(16'ha3bd);  // 07000090
        prog_h(16'h0508);  // 07000092
        prog_h(16'hbfc0);  // 07000094
        prog_h(16'h0500);  // 07000096
        prog_h(16'ha3de);  // 07000098
        prog_h(16'h0500);  // 0700009a
        prog_h(16'h7c0b);  // 0700009c
        prog_h(16'hcda6);  // 0700009e
        prog_h(16'h0508);  // 070000a0
        prog_h(16'hcdc6);  // 070000a2
        prog_h(16'h050c);  // 070000a4
        prog_h(16'hcde6);  // 070000a6
        prog_h(16'h0510);  // 070000a8
        prog_h(16'h6800);  // 070000aa
        go();
        wait_halt(12000, "e4b");
        expect_gpr(11, 32'hDEAD_BEEF, "e4b +32 first word");
        expect_gpr(12, 32'hCAFE_F00D, "e4b +32 copies cleanly");
        expect_gpr(13, 32'hDEAD_BEEF, "e4b +64 first word");
        expect_gpr(14, 32'hCAFE_F00D, "e4b +64 second word");
        expect_gpr(15, 32'hDEAD_BEEF, "e4b +64 third word corrupts");

        // E5: searches, both directions, found and exhausted, with the
        // documented one-bit-before pointer fix-up.
        restart();
        prog_h(16'h4140);  // 07000000
        prog_h(16'h7145);  // 07000002
        prog_h(16'h7800);  // 07000004
        prog_h(16'hbcc0);  // 07000006
        prog_h(16'h0500);  // 07000008
        prog_h(16'hbd40);  // 0700000a
        prog_h(16'h0001);  // 0700000c
        prog_h(16'hdd46);  // 0700000e
        prog_h(16'h0600);  // 07000010
        prog_h(16'h4140);  // 07000012
        prog_h(16'hdd46);  // 07000014
        prog_h(16'h0604);  // 07000016
        prog_h(16'hbd40);  // 07000018
        prog_h(16'h8000);  // 0700001a
        prog_h(16'hdd46);  // 0700001c
        prog_h(16'h0608);  // 0700001e
        prog_h(16'h4360);  // 07000020
        prog_h(16'ha380);  // 07000022
        prog_h(16'h0040);  // 07000024
        prog_h(16'ha3a0);  // 07000026
        prog_h(16'h0064);  // 07000028
        prog_h(16'hbfc0);  // 0700002a
        prog_h(16'h0500);  // 0700002c
        prog_h(16'ha3de);  // 0700002e
        prog_h(16'h0600);  // 07000030
        prog_h(16'h7c02);  // 07000032
        prog_h(16'h4962);  // 07000034
        prog_h(16'h019b);  // 07000036
        prog_h(16'h01bc);  // 07000038
        prog_h(16'h01dd);  // 0700003a
        prog_h(16'h01fe);  // 0700003c
        prog_h(16'h4360);  // 0700003e
        prog_h(16'ha380);  // 07000040
        prog_h(16'h0020);  // 07000042
        prog_h(16'h43a0);  // 07000044
        prog_h(16'hbfc0);  // 07000046
        prog_h(16'h0500);  // 07000048
        prog_h(16'ha3de);  // 0700004a
        prog_h(16'h0604);  // 0700004c
        prog_h(16'h7c02);  // 0700004e
        prog_h(16'h4a02);  // 07000050
        prog_h(16'h023e);  // 07000052
        prog_h(16'h025d);  // 07000054
        prog_h(16'h4363);  // 07000056
        prog_h(16'h438a);  // 07000058
        prog_h(16'h43a5);  // 0700005a
        prog_h(16'hbfc0);  // 0700005c
        prog_h(16'h0500);  // 0700005e
        prog_h(16'ha3de);  // 07000060
        prog_h(16'h0604);  // 07000062
        prog_h(16'h7c03);  // 07000064
        prog_h(16'h4a62);  // 07000066
        prog_h(16'h029e);  // 07000068
        prog_h(16'h02bb);  // 0700006a
        prog_h(16'h02dd);  // 0700006c
        prog_h(16'ha360);  // 0700006e
        prog_h(16'h001f);  // 07000070
        prog_h(16'ha380);  // 07000072
        prog_h(16'h0028);  // 07000074
        prog_h(16'h43a0);  // 07000076
        prog_h(16'hbfc0);  // 07000078
        prog_h(16'h0500);  // 0700007a
        prog_h(16'ha3de);  // 0700007c
        prog_h(16'h0608);  // 0700007e
        prog_h(16'h7c03);  // 07000080
        prog_h(16'h4ae2);  // 07000082
        prog_h(16'h031e);  // 07000084
        prog_h(16'h033b);  // 07000086
        prog_h(16'h00fc);  // 07000088
        prog_h(16'h6800);  // 0700008a
        go();
        wait_halt(12000, "e5");
        expect_gpr(11, 32'd0, "e5 up-find clears Z");
        expect_gpr(12, 32'd15, "e5 up-find points one bit before");
        expect_gpr(13, 32'd48, "e5 up-find keeps the found bit in r28");
        expect_gpr(14, 32'd116, "e5 up-find adds the skips to r29");
        expect_gpr(15, 32'h0500_0600, "e5 up-find r30");
        expect_gpr(16, 32'd1, "e5 up-miss sets Z");
        expect_gpr(17, 32'h0500_0608, "e5 up-miss walks past the string");
        expect_gpr(18, 32'd32, "e5 up-miss counted every bit");
        expect_gpr(19, 32'd1, "e5 down-miss sets Z");
        expect_gpr(20, 32'h0500_05FC, "e5 down-miss crossed the word");
        expect_gpr(21, 32'd31, "e5 down-miss offset past the edge");
        expect_gpr(22, 32'd15, "e5 down-miss skip count");
        expect_gpr(23, 32'd0, "e5 down-find clears Z");
        expect_gpr(24, 32'h0500_060C, "e5 down-find wraps the pointer up");
        expect_gpr(25, 32'd0, "e5 down-find offset");
        expect_gpr(7, 32'd40, "e5 down-find keeps the length");

        // E6: interrupts land inside long instructions. A bit string yields
        // between destination words with its own address saved and resumes
        // to a correct copy; a divide aborts mid-flight [manual Table 6-2]
        // and reruns cleanly after RETI.
        restart();
        prog_h(16'ha800);  // 07000000
        prog_h(16'h0018);  // 07000002
        prog_h(16'h4e60);  // 07000004
        prog_h(16'h9408);  // 07000006
        prog_h(16'h7680);  // 07000008
        prog_h(16'h02bc);  // 0700000a
        prog_h(16'h8a08);  // 0700000c
        prog_h(16'h4e61);  // 0700000e
        prog_h(16'h9404);  // 07000010
        prog_h(16'h76c0);  // 07000012
        prog_h(16'h4661);  // 07000014
        prog_h(16'h6400);  // 07000016
        prog_h(16'h4140);  // 07000018
        prog_h(16'h7145);  // 0700001a
        prog_h(16'h5800);  // 0700001c
        prog_h(16'hbcc0);  // 0700001e
        prog_h(16'h0500);  // 07000020
        prog_h(16'h4260);  // 07000022
        prog_h(16'h4121);  // 07000024
        prog_h(16'hd526);  // 07000026
        prog_h(16'h0000);  // 07000028
        prog_h(16'h4340);  // 0700002a
        prog_h(16'h4360);  // 0700002c
        prog_h(16'hbf80);  // 0700002e
        prog_h(16'h0000);  // 07000030
        prog_h(16'ha380);  // 07000032
        prog_h(16'h0800);  // 07000034
        prog_h(16'hbfa0);  // 07000036
        prog_h(16'h0500);  // 07000038
        prog_h(16'ha3bd);  // 0700003a
        prog_h(16'h2000);  // 0700003c
        prog_h(16'hbfc0);  // 0700003e
        prog_h(16'h0500);  // 07000040
        prog_h(16'ha3de);  // 07000042
        prog_h(16'h1000);  // 07000044
        prog_h(16'h7c0b);  // 07000046
        prog_h(16'h4122);  // 07000048
        prog_h(16'hd526);  // 0700004a
        prog_h(16'h0000);  // 0700004c
        prog_h(16'hbd40);  // 0700004e
        prog_h(16'h3000);  // 07000050
        prog_h(16'h4167);  // 07000052
        prog_h(16'h4123);  // 07000054
        prog_h(16'hd526);  // 07000056
        prog_h(16'h0000);  // 07000058
        prog_h(16'h254b);  // 0700005a
        prog_h(16'h4124);  // 0700005c
        prog_h(16'hd526);  // 0700005e
        prog_h(16'h0000);  // 07000060
        prog_h(16'h6800);  // 07000062
        dp = 'h7F10;   // handler 0xFFFFFE20 (level 2)
        prog_h(16'hbc20); prog_h(16'h0700);
        prog_h(16'ha021); prog_h(16'h0004);
        prog_h(16'h1801);
        for (gi = 0; gi < 64; gi = gi + 1) begin
            wram[('h1000 >> 1) + 2 * gi]     = 16'hA500 + gi[15:0];
            wram[('h1000 >> 1) + 2 * gi + 1] = 16'h5A00 + gi[15:0];
        end
        go();
        wait_status(16'h0001, 100000, "e6 approach");
        repeat (100) @(negedge clk);
        irq_level = 4'd2;
        irq_valid = 1'b1;
        repeat (40) @(negedge clk);
        irq_valid = 1'b0;
        wait_status(16'h0003, 100000, "e6 pre-divide");
        // Fire only once the divide has executed: pc has moved past it and
        // DIV_RUN is the only place a 6-clock pulse can land.
        while (dbg_pc !== 32'h0700005C) @(negedge clk);
        irq_valid = 1'b1;
        repeat (6) @(negedge clk);
        irq_valid = 1'b0;
        wait_halt(100000, "e6");
        expect_gpr(19, 32'd2, "e6 both interrupts serviced");
        expect_gpr(20, 32'h0700_0046, "e6 the string's own address saved");
        if (dut.gpr[21] === 32'd0 || dut.gpr[21] >= 32'h800
            || dut.gpr[21][4:0] !== 5'd0)
            $fatal(1, "e6: mid-string r28 was %0d, expected a word multiple inside (0,2048)",
                   dut.gpr[21]);
        expect_gpr(22, 32'h0700_005A, "e6 the divide aborted at itself");
        expect_gpr(10, 32'h06DB_6DB6, "e6 the rerun divide is right");
        expect_gpr(30, 32'd6, "e6 and so is the remainder");
        for (gi = 0; gi < 64; gi = gi + 1) begin
            if (wram[('h2000 >> 1) + 2 * gi] !== 16'hA500 + gi[15:0]
                || wram[('h2000 >> 1) + 2 * gi + 1] !== 16'h5A00 + gi[15:0])
                $fatal(1, "e6: copied word %0d is %04x%04x, expected %04x%04x",
                       gi, wram[('h2000 >> 1) + 2 * gi + 1],
                       wram[('h2000 >> 1) + 2 * gi],
                       16'h5A00 + gi[15:0], 16'hA500 + gi[15:0]);
        end

        // E7: the instruction cache. A restored fabricated entry executes
        // from the cache in place of ROM, a clear starting at entry 128
        // clears nothing, a targeted clear refills from ROM, a cached loop
        // runs correctly, the dump spills the documented 1,536-byte layout,
        // and an interrupt raised mid-dump waits for the walk to finish.
        restart();
        prog_h(16'ha800);  // 07000000
        prog_h(16'h0018);  // 07000002
        prog_h(16'hffff);  // 07000004
        prog_h(16'hffff);  // 07000006
        prog_h(16'h4145);  // 07000008
        prog_h(16'h181f);  // 0700000a
        prog_h(16'hffff);  // 0700000c
        prog_h(16'hffff);  // 0700000e
        prog_h(16'hcec6);  // 07000010
        prog_h(16'h35fc);  // 07000012
        prog_h(16'h4261);  // 07000014
        prog_h(16'h6400);  // 07000016
        prog_h(16'h4140);  // 07000018
        prog_h(16'h7145);  // 0700001a
        prog_h(16'h7800);  // 0700001c
        prog_h(16'hbcc0);  // 0700001e
        prog_h(16'h0500);  // 07000020
        prog_h(16'h4260);  // 07000022
        prog_h(16'hafff);  // 07000024
        prog_h(16'hffe4);  // 07000026
        prog_h(16'h01ca);  // 07000028
        prog_h(16'hbd60);  // 0700002a
        prog_h(16'h0500);  // 0700002c
        prog_h(16'ha16b);  // 0700002e
        prog_h(16'h4022);  // 07000030
        prog_h(16'h7178);  // 07000032
        prog_h(16'hafff);  // 07000034
        prog_h(16'hffd4);  // 07000036
        prog_h(16'h01ea);  // 07000038
        prog_h(16'hbd60);  // 0700003a
        prog_h(16'h0810);  // 0700003c
        prog_h(16'ha16b);  // 0700003e
        prog_h(16'hff03);  // 07000040
        prog_h(16'h7178);  // 07000042
        prog_h(16'hafff);  // 07000044
        prog_h(16'hffc4);  // 07000046
        prog_h(16'h020a);  // 07000048
        prog_h(16'hbd60);  // 0700004a
        prog_h(16'h0010);  // 0700004c
        prog_h(16'ha16b);  // 0700004e
        prog_h(16'h0103);  // 07000050
        prog_h(16'h7178);  // 07000052
        prog_h(16'hafff);  // 07000054
        prog_h(16'hffb4);  // 07000056
        prog_h(16'h022a);  // 07000058
        prog_h(16'h4140);  // 0700005a
        prog_h(16'h418a);  // 0700005c
        prog_h(16'h4541);  // 0700005e
        prog_h(16'h459f);  // 07000060
        prog_h(16'h95fc);  // 07000062
        prog_h(16'h024a);  // 07000064
        prog_h(16'h5800);  // 07000066
        prog_h(16'hbd60);  // 07000068
        prog_h(16'h0500);  // 0700006a
        prog_h(16'ha16b);  // 0700006c
        prog_h(16'h3012);  // 0700006e
        prog_h(16'h7178);  // 07000070
        prog_h(16'h7800);  // 07000072
        prog_h(16'h4160);  // 07000074
        prog_h(16'h7178);  // 07000076
        prog_h(16'hafff);  // 07000078
        prog_h(16'hff90);  // 0700007a
        prog_h(16'h028a);  // 0700007c
        prog_h(16'h6800);  // 0700007e
        dp = 'h7F10;   // handler 0xFFFFFE20 (level 2)
        prog_h(16'hbc20); prog_h(16'h0700);
        prog_h(16'ha021); prog_h(16'h0010);
        prog_h(16'h1801);
        for (gi = 0; gi < 768; gi = gi + 1) wram[('h4000 >> 1) + gi] = 16'h0000;
        wram['h2004] = 16'h4149;   // entry 1 subblock 0: movImm 9, r10
        wram['h2005] = 16'h181F;   //                     jmp [r31]
        wram['h2202] = 16'hC000;   // entry 1 tag: valid0 | (T >> 10)
        wram['h2203] = 16'h0041;
        go();
        // The first dump write marks the walk running; hold the request up
        // so acceptance can only come from the FETCH1 after it finishes.
        while (!(req && we && a == 26'h2801800)) @(negedge clk);
        irq_level = 4'd2;
        irq_valid = 1'b1;
        repeat (3000) @(negedge clk);
        irq_valid = 1'b0;
        wait_halt(100000, "e7");
        expect_gpr(14, 32'd5, "e7 uncached runs the ROM");
        expect_gpr(15, 32'd9, "e7 the restored entry executes from cache");
        expect_gpr(16, 32'd9, "e7 a clear at entry 128 clears nothing");
        expect_gpr(17, 32'd5, "e7 a targeted clear refills from ROM");
        expect_gpr(18, 32'd10, "e7 the cached loop counts");
        expect_gpr(20, 32'd5, "e7 disabled again, ROM wins");
        expect_gpr(19, 32'd1, "e7 the mid-dump interrupt was serviced once");
        expect_gpr(22, 32'd0, "e7 and only after the dump finished");
        if (wram['h1804] !== 16'h4145 || wram['h1805] !== 16'h181F)
            $fatal(1, "e7: dumped entry 1 data is %04x %04x, expected the ROM refill",
                   wram['h1804], wram['h1805]);
        if (wram['h1A02] !== 16'hC000 || wram['h1A03] !== 16'h0041)
            $fatal(1, "e7: dumped entry 1 tag is %04x%04x, expected 0041c000",
                   wram['h1A03], wram['h1A02]);
        if (wram['h182E] !== 16'h418A || wram['h182F] !== 16'h4541)
            $fatal(1, "e7: dumped loop subblock is %04x %04x",
                   wram['h182E], wram['h182F]);
        if (wram['h1A16] !== 16'hC000 || wram['h1A17] !== 16'h00C1)
            $fatal(1, "e7: dumped loop tag is %04x%04x, expected 00c1c000",
                   wram['h1A17], wram['h1A16]);
        if (wram['h1AFE] !== 16'h0000 || wram['h1AFF] !== 16'h0000)
            $fatal(1, "e7: entry 127 should dump as cleared zeros");

        // E8: the address trap. With AE set and ADTRE on an instruction,
        // the trap fires before that instruction's fetch with restore at
        // current PC and AE cleared on entry; the handler steps EIPC to
        // resume past it. With AE clear the same address executes.
        restart();
        prog_h(16'ha800);  // 07000000
        prog_h(16'h0014);  // 07000002
        prog_h(16'h7684);  // 07000004
        prog_h(16'h76a0);  // 07000006
        prog_h(16'h76c5);  // 07000008
        prog_h(16'h7500);  // 0700000a
        prog_h(16'h4502);  // 0700000c
        prog_h(16'h7100);  // 0700000e
        prog_h(16'h4661);  // 07000010
        prog_h(16'h6400);  // 07000012
        prog_h(16'h4140);  // 07000014
        prog_h(16'h7145);  // 07000016
        prog_h(16'h7800);  // 07000018
        prog_h(16'h4260);  // 0700001a
        prog_h(16'hbd60);  // 0700001c
        prog_h(16'h0700);  // 0700001e
        prog_h(16'ha16b);  // 07000020
        prog_h(16'h002e);  // 07000022
        prog_h(16'h7179);  // 07000024
        prog_h(16'ha180);  // 07000026
        prog_h(16'h3000);  // 07000028
        prog_h(16'h7185);  // 0700002a
        prog_h(16'h41a3);  // 0700002c
        prog_h(16'h41a7);  // 0700002e
        prog_h(16'h41c5);  // 07000030
        prog_h(16'ha180);  // 07000032
        prog_h(16'h1000);  // 07000034
        prog_h(16'h7185);  // 07000036
        prog_h(16'hbd60);  // 07000038
        prog_h(16'h0700);  // 0700003a
        prog_h(16'ha16b);  // 0700003c
        prog_h(16'h0044);  // 0700003e
        prog_h(16'h7179);  // 07000040
        prog_h(16'h4202);  // 07000042
        prog_h(16'h4209);  // 07000044
        prog_h(16'h6800);  // 07000046
        dp = 'h7FE0;   // handler 0xFFFFFFC0
        prog_h(16'hbc20); prog_h(16'h0700);
        prog_h(16'ha021); prog_h(16'h0004);
        prog_h(16'h1801);
        go();
        wait_halt(6000, "e8");
        expect_gpr(20, 32'h0000_FFC0, "e8 the address trap code");
        expect_gpr(21, 32'h0700_002E, "e8 EIPC is the trapped instruction");
        expect_gpr(22, 32'h0000_5000, "e8 entry sets EP|ID and clears AE");
        expect_gpr(13, 32'd3, "e8 the trapped instruction never ran");
        expect_gpr(14, 32'd5, "e8 execution resumed past it");
        expect_gpr(16, 32'd9, "e8 no trap once AE is clear");
        expect_gpr(19, 32'd1, "e8 exactly one trap");

        // T2: the new charges, measured the way T1 measures. Marker pairs
        // cost 7 at one-wait ROM; each expected value is the instruction's
        // charge from cpu.v's tables plus that 7.
        restart();
        mark_n = 0;
        prog_h(16'h7800);  // 07000000
        prog_h(16'hbcc0);  // 07000002
        prog_h(16'h0500);  // 07000004
        prog_h(16'h4120);  // 07000006
        prog_h(16'hbd60);  // 07000008
        prog_h(16'h0200);  // 0700000a
        prog_h(16'ha16b);  // 0700000c
        prog_h(16'h0024);  // 0700000e
        prog_h(16'h4141);  // 07000010
        prog_h(16'hd54b);  // 07000012
        prog_h(16'h0000);  // 07000014
        prog_h(16'hbda0);  // 07000016
        prog_h(16'h3f80);  // 07000018
        prog_h(16'hbdc0);  // 0700001a
        prog_h(16'h4000);  // 0700001c
        prog_h(16'hbe00);  // 0700001e
        prog_h(16'h1111);  // 07000020
        prog_h(16'ha210);  // 07000022
        prog_h(16'h2222);  // 07000024
        prog_h(16'hde06);  // 07000026
        prog_h(16'h0100);  // 07000028
        prog_h(16'h4200);  // 0700002a
        prog_h(16'hde06);  // 0700002c
        prog_h(16'h0700);  // 0700002e
        prog_h(16'hbe00);  // 07000030
        prog_h(16'hf0f1);  // 07000032
        prog_h(16'ha210);  // 07000034
        prog_h(16'hf0f0);  // 07000036
        prog_h(16'hde06);  // 07000038
        prog_h(16'h0200);  // 0700003a
        prog_h(16'hde06);  // 0700003c
        prog_h(16'h0204);  // 0700003e
        prog_h(16'h4521);  // 07000040
        prog_h(16'hd526);  // 07000042
        prog_h(16'h0000);  // 07000044
        prog_h(16'hf9e0);  // 07000046
        prog_h(16'h2400);  // 07000048
        prog_h(16'h4521);  // 0700004a
        prog_h(16'hd526);  // 0700004c
        prog_h(16'h0000);  // 0700004e
        prog_h(16'hf9ee);  // 07000050
        prog_h(16'h3000);  // 07000052
        prog_h(16'h4521);  // 07000054
        prog_h(16'hd526);  // 07000056
        prog_h(16'h0000);  // 07000058
        prog_h(16'hf9ee);  // 0700005a
        prog_h(16'h2800);  // 0700005c
        prog_h(16'h4521);  // 0700005e
        prog_h(16'hd526);  // 07000060
        prog_h(16'h0000);  // 07000062
        prog_h(16'hea06);  // 07000064
        prog_h(16'h0100);  // 07000066
        prog_h(16'h4521);  // 07000068
        prog_h(16'hd526);  // 0700006a
        prog_h(16'h0000);  // 0700006c
        prog_h(16'hf9ae);  // 0700006e
        prog_h(16'h1000);  // 07000070
        prog_h(16'h4521);  // 07000072
        prog_h(16'hd526);  // 07000074
        prog_h(16'h0000);  // 07000076
        prog_h(16'hf9ae);  // 07000078
        prog_h(16'h1c00);  // 0700007a
        prog_h(16'h4521);  // 0700007c
        prog_h(16'hd526);  // 0700007e
        prog_h(16'h0000);  // 07000080
        prog_h(16'h4340);  // 07000082
        prog_h(16'h4360);  // 07000084
        prog_h(16'ha380);  // 07000086
        prog_h(16'h0040);  // 07000088
        prog_h(16'hbfa0);  // 0700008a
        prog_h(16'h0500);  // 0700008c
        prog_h(16'ha3bd);  // 0700008e
        prog_h(16'h0300);  // 07000090
        prog_h(16'hbfc0);  // 07000092
        prog_h(16'h0500);  // 07000094
        prog_h(16'ha3de);  // 07000096
        prog_h(16'h0200);  // 07000098
        prog_h(16'h4521);  // 0700009a
        prog_h(16'hd526);  // 0700009c
        prog_h(16'h0000);  // 0700009e
        prog_h(16'h7c0b);  // 070000a0
        prog_h(16'h4521);  // 070000a2
        prog_h(16'hd526);  // 070000a4
        prog_h(16'h0000);  // 070000a6
        prog_h(16'h4360);  // 070000a8
        prog_h(16'ha380);  // 070000aa
        prog_h(16'h0020);  // 070000ac
        prog_h(16'h43a0);  // 070000ae
        prog_h(16'hbfc0);  // 070000b0
        prog_h(16'h0500);  // 070000b2
        prog_h(16'ha3de);  // 070000b4
        prog_h(16'h0700);  // 070000b6
        prog_h(16'h4521);  // 070000b8
        prog_h(16'hd526);  // 070000ba
        prog_h(16'h0000);  // 070000bc
        prog_h(16'h7c02);  // 070000be
        prog_h(16'h4521);  // 070000c0
        prog_h(16'hd526);  // 070000c2
        prog_h(16'h0000);  // 070000c4
        prog_h(16'h4380);  // 070000c6
        prog_h(16'h4521);  // 070000c8
        prog_h(16'hd526);  // 070000ca
        prog_h(16'h0000);  // 070000cc
        prog_h(16'h7c0b);  // 070000ce
        prog_h(16'h4521);  // 070000d0
        prog_h(16'hd526);  // 070000d2
        prog_h(16'h0000);  // 070000d4
        prog_h(16'h4182);  // 070000d6
        prog_h(16'h4162);  // 070000d8
        prog_h(16'h7178);  // 070000da
        prog_h(16'h4521);  // 070000dc
        prog_h(16'hd526);  // 070000de
        prog_h(16'h0000);  // 070000e0
        prog_h(16'hf9e0);  // 070000e2
        prog_h(16'h2400);  // 070000e4
        prog_h(16'hf9e0);  // 070000e6
        prog_h(16'h2400);  // 070000e8
        prog_h(16'hf9e0);  // 070000ea
        prog_h(16'h2400);  // 070000ec
        prog_h(16'hf9e0);  // 070000ee
        prog_h(16'h2400);  // 070000f0
        prog_h(16'hf9e0);  // 070000f2
        prog_h(16'h2400);  // 070000f4
        prog_h(16'hf9e0);  // 070000f6
        prog_h(16'h2400);  // 070000f8
        prog_h(16'hf9e0);  // 070000fa
        prog_h(16'h2400);  // 070000fc
        prog_h(16'hf9e0);  // 070000fe
        prog_h(16'h2400);  // 07000100
        prog_h(16'h459f);  // 07000102
        prog_h(16'h95d8);  // 07000104
        prog_h(16'h4521);  // 07000106
        prog_h(16'hd526);  // 07000108
        prog_h(16'h0000);  // 0700010a
        prog_h(16'h6800);  // 0700010c
        go();
        wait_halt(60000, "t2");
        if (mark_n !== 16)
            $fatal(1, "t2: %0d markers, expected 16", mark_n);
        // XH is fetch-bound: max(1, 4)
        expect_delta(1, 4 + 7, "t2 xh");
        expect_delta(2, 9 + 7, "t2 mpyhw");
        expect_delta(3, 22 + 7, "t2 rev");
        // CAXI: max(26, 4) plus one wait on each of its four accesses
        expect_delta(4, 30 + 7, "t2 caxi");
        expect_delta(5, 22 + 7, "t2 addf");
        expect_delta(6, 44 + 7, "t2 divf");
        // MOVBSU, 64 aligned WRAM bits: 22+16 first invocation, 2+12 next
        expect_delta(8, 52 + 7, "t2 movbsu");
        // SCH1BSU, 32 bits: 26 + one word read + the scan
        expect_delta(10, 31 + 7, "t2 search");
        // Length zero: the documented 20
        expect_delta(12, 20 + 7, "t2 movbsu nothing");
        // Cached warm pass: 8 XH at 2 each (hit fetches cost 1 per
        // halfword), the loop exit (addImm 1, bne untaken 1, addImm 1) and
        // the closing stH at 3 -- plus 5 for that closing marker's own
        // subblock, the one fetch the first pass never warmed.
        expect_delta(15, 22 + 5, "t2 cached warm pass");
        if (marks[14] - marks[13] < marks[15] - marks[14] + 20)
            $fatal(1, "t2 cold pass should pay the fills: cold %0d, warm %0d",
                   marks[14] - marks[13], marks[15] - marks[14]);

        // D-WAIT: a word load served by a device that answers late. Both
        // halfword answers are correct on the bus; what the CPU may not do
        // is wait for the second one before taking the first, because by
        // then rdata carries the second. Taking it late reads the high half
        // twice -- the pointer 0x050054b0 comes back as 0x05000500 -- which
        // is what sent VUEngine's Game::start down its already-started
        // branch and rebooted the machine into a black screen. The 32-bit
        // instructions here are fetched through the same waits, so the
        // fetch path's own two halfwords are on trial too.
        restart();
        prog_h(16'hbcc0); prog_h(16'h0500);   // movhi 0x0500, r0, r6
        prog_h(16'ha0c6); prog_h(16'h0200);   // movea 0x0200, r6, r6
        prog_h(16'hcd46); prog_h(16'h0000);   // ld.w  0[r6], r10
        prog_h(16'h6800);                     // halt
        wram['h0100] = 16'h54b0;              // 0x05000200, the low half
        wram['h0101] = 16'h0500;              // 0x05000202, the high half
        waits_on = 1'b1;
        go();
        wait_halt(20000, "dwait");
        waits_on = 1'b0;
        expect_gpr(10, 32'h0500_54b0, "dwait word load through wait states");

        // The built images, run whole. Their own checks judge; the status
        // word carries the verdict and names the failing check on a spin.
        run_rom("cpu-alu", 2048, 200000);
        run_rom("cpu-branch", 1024, 200000);
        run_rom("busmap", 1024, 200000);
        run_rom("cpu-except", 1024, 200000);
        run_rom("cpu-ext", 512, 200000);
        run_rom("cpu-float", 1024, 400000);
        run_rom("cpu-bitstring", 1024, 400000);
        run_rom("cpu-cache", 512, 400000);
        run_rom("cpu-longint", 512, 2000000);
        run_rom("cpu-adtre", 512, 200000);

        // The 2MB cartridge, whose checks read markers placed for where they
        // land in the SDRAM. Run here against the behavioral memory, this
        // judges the ROM's own arithmetic -- its addresses, its constants and
        // its mirror -- so a failing check on hardware points at the
        // controller rather than at the program.
        run_rom("cart-size", 1048576, 400000);

        // The timer ROM's check phase, through the real timer and the
        // real interrupt path: its status 0x0000 write means every check
        // passed and the seconds display armed. The seconds themselves
        // are far too slow to simulate; the hardware run judges those.
        run_rom_status("timer", 1024, 16'h0000, 400000);

        // The pad ROM, through the real game pad and the real bus. Its
        // self-test publishes 0x600D only after the data registers came up
        // zero, a software read alone filled them, a hardware read reported
        // busy and finished, and the two agreed -- the one order that can
        // tell the two read paths apart, since they share a register.
        // Driving a second value afterwards proves the loop re-reads rather
        // than latching once.
        pad_buttons = 16'h1236;
        run_rom_status("pad", 1024, 16'h600d, 400000);
        wait_status(16'h1236, 400000, "pad");
        pad_buttons = 16'hc0de;
        wait_status(16'hc0de, 400000, "pad");
        if (pad_irq !== 1'b0)
            $fatal(1, "pad: the key interrupt fired on a report that sets SGN");

        $finish;
    end

    initial begin
        #30_000_000;
        $fatal(1, "timed out");
    end

endmodule
